flexcompute/tidy3d

.pylintrc
lint.py
test_static.sh
tests/test_plugins.py
tidy3d/components/mode.py
tidy3d/components/monitor.py
tidy3d/components/simulation.py
tidy3d/components/types.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/mode/solver.py
tidy3d/plugins/mode/transforms.py

Latest solver updates from old tidy3d
bend modes in ModeSpec
Mode solver always takes grid boundaries instead of grid_size so that it works with nonuniform coords

Bringing in upgraded mode solver

---

tidy3d/web/auth.py

When user tries to login in current version but supplies wrong password, the session exits.
With this change, it just prints the error and asks again.
I think this is preferred behavior?

dont error when user cant login

---

tidy3d/components/simulation.py
tidy3d/components/viz.py

before, adding a PEC would change the colorbar in plot_eps to include `tidy3d.constants.pec_val` now it does not.

PEC structures do not affect colorbar in plot_eps

---

lint.py
tests/requirements.txt
tests/test_components.py
tidy3d/components/data.py
tidy3d/components/geometry.py
tidy3d/components/medium.py
tidy3d/components/simulation.py
tidy3d/components/source.py
tidy3d/plugins/mode/derivatives.py
tidy3d/plugins/mode/solver.py
tidy3d/plugins/near2far/near2far.py
tox.ini

Tox tests now check for
* clean lint.
* clean diff from black
Blacked code using updated black, adds spacing around `**`

Stricter Tests

---

CHANGELOG.md
tests/_test_fit_web.py
tests/test_plugins.py
tests/test_plugins_web.py
tidy3d/plugins/__init__.py
tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/dispersion/fit_web.py

More error handling in StableDispersiveFitter
Allow to load dispersive data directly by providing URL to txt or csv file
Add tunable eps_inf as a variable for optimization
Allow to set frequency range for fitting

Fitter improvement

---

tidy3d/components/viz.py

changed color scheme

---

tidy3d/__init__.py
tidy3d/components/__init__.py
tidy3d/components/geometry.py
tidy3d/components/simulation.py
tidy3d/components/source.py
tidy3d/components/types.py
tidy3d/constants.py

Previously, we defined `td.inf` to point to a `LARGE_NUMBER` defined in `components/constants.py`.  This got the job done but had a few downsides:
* Was not explicit  in the data files whether a number was just large or was supposed to be infinite.
* Needed to still be careful we got expected behavior if comparing this with another number that happened to be large (like frequencies in Hz).
This PR sets `td.inf = np.inf`, which seems to write to json fine.
The visualizations also render correctly.
I had to add a `@staticmenthod` in `Geometry` to evaluate the infinity values as `LARGE_NUMBER` in before setting axes limits as matplotlib could not handle this.
Everything else should be good to go.

uses numpy inf instead of LARGE_NUMBER

---

CHANGELOG.md
requirements.txt
tests/test_components.py
tests/test_grid.py
tidy3d/components/data.py
tidy3d/components/geometry.py
tidy3d/components/grid.py
tidy3d/components/mode.py
tidy3d/components/simulation.py
tidy3d/components/validators.py
tidy3d/components/viz.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/mode/solver.py
tidy3d/web/config.py

Symmetries specified in a `ModeSpec` now generally work, but there are a lot of possible edge cases...
Also, I have built `release-22.1.4` on the server with all the changes from last week, and set it as default here.

Bringing back symmetries into the mode solver

---

tidy3d/components/data.py

This is needed to make the simple adjoint test pass. See also the comment in the changed file.

Removing the user-defined source phase from normalization

---

tests/test_IO.py
tests/test_components.py
tests/test_grid.py
tests/test_plugins.py
tests/utils.py
tidy3d/components/simulation.py

Not much to see here.
`run_time > 0` is required now.
Changed all of the tests to include `run_time` if not supplied so they pass.

makes run time a required parameter

---

CHANGELOG.md
tests/test_plugins.py
tidy3d/plugins/near2far/near2far.py

`Near2Far` supports vectorized inputs in the observation coordinates; uses vectorized calculations where advantageous. Output far fields are now `xarray` datasets.
Note that the use of the progress bar in the function `_radiation_vectors_for_surface` is a bit ugly. This was to avoid a limitation of the progress bar: even when it is disabled (e.g. when only a single observation point is given) it still prints a bunch of blank lines. This is an issue for the functions which compute far fields in Cartesian coordinates. The "ugly" way only invokes the progress bar when more than one `theta` is given.

Near2Far vectorization

---

tidy3d/web/container.py
tidy3d/web/webapi.py

So this is looking pretty good on the front end, but needs some testing and a bit of refinement.
How it works now:
1. Use console.status (running man animation) to loop through pre-processing statuses.
2. Log that the solver is starting until we can successfully grab the % done data.
3. Progressbar through % done and print field_Decay in progress bar description.
4. Use console.status (running man animation) to loop through post-processing statuses
Simplifies a lot.
Job uses web.monitor() now.
Remaining issues:
* Takes a long time to start getting % done, by which point the task is already completed.   Need to either reduce this amount of time or change the message.
* Needs some more testing by us before I feel confident releasing it.

% Done Monitoring

---

tests/test_components.py
tests/test_plugins.py
tidy3d/__init__.py
tidy3d/components/__init__.py
tidy3d/components/data.py
tidy3d/components/monitor.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/web/config.py

- Remove current ModeSolverMonitor and ModeSolverData
- Introduce instead ModeFieldMonitor and ModeFieldData
- Put mode_spec and freqs as fields in ModeSolver
- ModeSolverData is the return of .solve and stores the ModeSolver simulation, plane, and mode_spec as well as well as the ModeFieldData and ModeIndexData
Notes:
- ModeSolverData is not storing the entire ModeSolver instance because of circular dependence in ModeSolver.solve which returns ModeSolverData...
- Yet to add a field plotting method which will use a lot of the same code from SimulationData

Reorganizing of ModeSolver and ModeSolverData

---

.pylintrc
test_local.sh
tests/test_sidewall.py
tidy3d/components/geometry.py

More Validators for PolySlab to make sure the base polygon is valid
Validator to make sure no vertices crossing during extrusion with sidewall
Change "inside" function in geometry to include boundaries
Implement itersection_side for slanted PolySlab

Slanted PolySlab implementation

---

tidy3d/components/data.py

I dont know if we need this as long as h5py version is 3.0.0 or later.
I already changed requirements.txt to include this version requirement.

if the bytes string is already a string, just return it

---

tests/_test_web.py
tests/test_components.py
tests/utils.py
tidy3d/components/data.py
tidy3d/plugins/dispersion/fit_web.py
tidy3d/plugins/smatrix/smatrix.py
tidy3d/web/__init__.py
tidy3d/web/auth.py
tidy3d/web/webapi.py

Credential folder only created when needed
Maximum attempts in authentication while loops
Authentication only called when needed, and checks if already done

webapi fixes

---

tidy3d/components/simulation.py
tidy3d/components/viz.py

*  only uses medium info if shapes found in intersection.
* ` simulation` caches `medium` and `medium_map` now, with performance gains for many structures..

plotly much faster, is smarter about checking medium

---

tests/_test_web.py
tidy3d/web/config.py
tidy3d/web/httputils.py
tidy3d/web/task.py
tidy3d/web/webapi.py

SCEM-205: upgrade webapi

---

tidy3d/components/data.py

```python
from tidy3d import SimulationData
sim_data = SimulationData.from_file("something.hdf5")
print(sim_data.normalized)
sim_data.to_file("something2.hdf5")
sim_data2 = SimulationData.from_file("something2.hdf5")
[10:39:57] ERROR    Data from this file is already normalized.  log.py:33
Instead, load `.from_file()` with
`normalize_index=None.
sim_data2 = SimulationData.from_file("something2.hdf5", normalize_index=None)
```
Let me know if we want to change behavior here.

normalize sim data upon .from_file()

---

tests/_test_web.py
tidy3d/web/__init__.py
tidy3d/web/httputils.py
tidy3d/web/webapi.py

Removing unnecessary _upload_task function (duplicate of upload)
Log the estimated cost upon task upload
Update the web tests
This is my version of #300 . I had done most of the work yesterday but didn't push and then An made a different PR.

Adding estimate_cost to webapi

---

tidy3d/components/simulation.py
tidy3d/plugins/plotly/simulation.py

This makes it much faster for most cases, like `.plot()` with many structures

Only filter and merge in plot_structures_eps with transparency

---

tests/test_grid.py
tidy3d/components/simulation.py

Previously we always put the N/2 - th grid boundary at the simulation center. Now we just put the simulation center at `sum(dls) / 2`, which makes more sense (even with respect to the description of the `dls` in the `grid_size` Field), and is also less constrictive.

Changing custom dls centering

---

tidy3d/components/medium.py

Makes this explicit and fixes `nan` coming from `inf * 0` in `PoleResidue`

eps_model eval at `td.inf` if freq is None

---

tidy3d/components/base.py
tidy3d/components/data.py
tidy3d/components/geometry.py
tidy3d/components/medium.py
tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/webplots/app.py
tidy3d/plugins/webplots/data.py

These get passed to the `init` functions.
Example
```python
class Box(Geometry):
@classmethod
def from_bounds(cls, rmin: Coordinate, rmax: Coordinate, **kwargs):
def get_center(pt_min: float, pt_max: float) -> float:
"""Returns center point based on bounds along dimension."""
if np.isneginf(pt_min) and np.isposinf(pt_max):
return 0.0
return (pt_min + pt_max) / 2.0
center = tuple(get_center(pt_min, pt_max) for pt_min, pt_max in zip(rmin, rmax))
size = tuple((pt_max - pt_min) for pt_min, pt_max in zip(rmin, rmax))
return cls(center=center, size=size, **kwargs)
```
Doing it this way means you can call 
```python
sim = Simulation.from_bounds(rmin=(0,0,0), rmax=(1,1,1), grid_size=(.1, .1, .1), run_time=1e-12)
mon = FluxMonitor.from_bounds(rmin=(0,0,0), rmax=(0,1,1), freqs=[1e14])
``` …

added kwargs to alternate constructor classmethods

---

tidy3d/components/simulation.py
tidy3d/components/viz.py

add opacity kwrgs for monitor and source in sim.plot

---

tidy3d/plugins/smatrix/smatrix.py

To compute S_ii elements in the S matrix, we need to place a monitor at approximately the same position as the i-th source.  They could not be at the exact same location due to numerical issues.  So we decided to place the monitor one grid cell away.
This only supported uniform mesh, because we knew what this grid cell was. In nonuniform, choosing this distance becomes a bit more tricky.
For now, I just made the distance a parameter (default of 0.1 um) that is a `Field` of the `ComponentModeler` and can be changed by the user. I added a bit of description on how to do this.
This will eliminate errors from using `ComponentModeler` when `nonunform` is default.  We may want to revisit this PR to come up with a way to choose this distance automatically based on the local `grid_size`.
At the …

variable distance between injection source and monitor

---

tests/test_components.py
tidy3d/components/base.py

Overwrites the `Tidy3dBaseModel.copy()` method to make default value of `deep=True`.
More common use case and means people dont have to remember to add it when copying an object for modification.

copy is deep by default

---

tidy3d/components/monitor.py
tidy3d/components/source.py

Default
source_alpha = 1
source_alpha=0.1

apply sim.plot and sim.plot_eps opacity kwargs to arrows

---

tests/test_meshgenerate.py
tidy3d/components/grid/grid_spec.py
tidy3d/components/grid/mesher.py
tidy3d/components/simulation.py
tidy3d/version.py

- The first structure in the structures list is the simulation, so the center and size can be taken from there - don't need to be passed
- The symmetry on the other hand needs to be passed, because we need to truncate the domain to the symmetry quadrant when we do the auto meshing

Rearranging make_coords_initial and fixing symmetry bug in auto mesh

---

requirements/dev.txt
tests/test_static.py
tidy3d/components/base.py
tidy3d/components/simulation.py
tidy3d/static.py

* Adds `Simulation._hash` private attribute.  If this is not `None`, the `__hash__` function will return it rather than hashing `self.json()`.  This can provide significant speedup for `.grid()` and other `@lru_cache`ed properties.
* `tidy3d/static.py` defines a context manager `MakeStatic` and a decorator `make_static`, which can be used as follows.
```python
with MakeStatic(sim) as sim_static:
```
```python
@make_static
def formerly_slow(sim, arg2, kwarg1=1.0):
```
the context manager checks that the hash of `sim` is the same before and after the context, catching instances where anything contained in the `Simulation` may have been mutated.
Speed tests confirm that this provides significant speedup.

Add ability to cache simulation hash in static context for speedup.

---

tests/test_sidewall.py
tidy3d/components/geometry.py
tidy3d/components/simulation.py

I made the bounds property less strict in the case of dilution or slant. The bounds should always fully contain the PolySlab, even though they may not be as tight as possible. They are much faster to compute though as no calls to the base and top polygons are needed.

Speeding up PolySlab.bounds 

---

tests/test_meshgenerate.py
tidy3d/components/geometry.py
tidy3d/components/grid/mesher.py
tidy3d/components/simulation.py

- Reorganized parse_structures to mitigate various inefficiencies revealed when profiling various simulations with > 1k structures.
- Using shapely in-built Rtree to speed up containment parsing. Currently still the bottleneck in many cases, but much better than before. Perhaps explore different spatial indexing schemes in the future.
- A second filtering of the interval sizes is done after all the structure containment is handled, to use the smallest step from all structures that are actually present in the meshing, in case some got completely covered.
- Split up the tests that were in `test_parse_structures` into separate ones; added a test with a gold slab, and also that if the gold slab is completely covered, its permittivity will be ignored when filtering the smallest interval size. …

Faster mesh generation

---

tests/sims/simulation_1_3_3.json
tests/sims/simulation_1_4_0.json
tests/test_IO.py
tidy3d/__init__.py
tidy3d/updater.py
tidy3d/version.py

Running `test_IO.py` will now also export a simulation file with the current version name to `tests/sims`. Then, `test_simulation_updater` will try to update all of these files to the current version. This should alert us if there's any issue with the conversion (although it's contingent on `sim_all` having as many example components as possible).
Infinity seems to work fine.

Simulation updater for loading old json versions

---

tests/sims/simulation_1_4_0.json
tests/test_components.py
tidy3d/components/monitor.py

Assuming for now that permittivity monitors are not downsampled.
Associated issue: https://github.com/flexcompute/tidy3d-core/issues/68
Associated backend PR: https://github.com/flexcompute/tidy3d-core/pull/63
Notebook (will eventually need to modify to run via web, not locally):
https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/shash/monitor_downsampling/docs/source/notebooks/MonitorDownsampling.ipynb

Monitor downsampling

---

tests/sims/simulation_1_4_0.json
tests/sims/simulation_1_4_1.json
tests/sims/simulation_1_5_0.json
tests/test_IO.py
tidy3d/components/geometry.py
tidy3d/updater.py
tidy3d/version.py

A bit of reorganization so we dont abuse pydantic validators.
* Removed `Geometry.center` and added it as another abstract class that `Box`, `Sphere`, and `Cylinder` inherit from.
* Removed `Planar.length` and added it explicitly to `Cylinder`.
* Introduced abstract `center_axis` and `length_axis` properties to `Planar`, which must be implemented in subclasses for the planar logic to function appropriately.
Result is that validators are no longer used to set fields.
Note that version was changed to 1.5.0 because it introduces a minor schema change (no longer a "center" and "length" in PolySlab schema).

Reorganize geometry.py

---

tests/test_boundaries.py
tests/test_grid.py
tidy3d/components/base.py
tidy3d/components/data.py
tidy3d/components/geometry.py
tidy3d/components/grid/grid.py
tidy3d/components/monitor.py
tidy3d/components/simulation.py
tidy3d/components/source.py
tidy3d/components/structure.py
tidy3d/components/types.py

* moves `TYPE_TAG_STR` to `types.py`
* introduces `annotate_type(UnionType)` function to wrap the adding of discriminator to `Union[...]` type.
* puts annotations directly in `Field()` definitions with `Tuple[Union[], ...]` fields
* adds discriminator to `pd.Fiedl()` for `Union[]` fields.

refactored type annotation to be able to resuse union types

---

tests/sims/simulation_1_5_0.json
tidy3d/components/mode.py
tidy3d/plugins/mode/solver.py
tidy3d/updater.py

Previous use: `sort_by: Literal["largest_neff", "te_fraction", "tm_fraction"]`. Not very convenient because what you typically want to do is not e.g. inject the te mode with the largest te fraction, but rather inject e.g. the fundamental (largest neff) mode that is predominantly te polarized.
New use: `filter_pol: Literal["te", "tm"]`. If None, just sort by largest neff. If e.g. `"te"`, then the modes with te-fraction larger than 0.5 are placed first (ordered by largest neff), then the other modes are grouped second (again ordered by largest neff).
I also added a convenience function for the updater for recursively updating the dict.
Fixes #298

Sort_by -> filter_pol in ModeSpec, updated updater

---

test_local.sh
tests/test_data.py
tidy3d/components/boundary.py
tidy3d/components/data.py

- Complex-valued fields allowed in `ScalarFieldTimeData`
- Added missing frontend tests in test_local
- Added clarification in docstring for Bloch boundaries
Related issue: https://github.com/flexcompute/tidy3d-core/issues/89

Complex-valued field fixes

---

tests/test_data_arrays.py
tests/test_data_monitor.py
tests/test_data_sim.py
tidy3d/components/data/README.md
tidy3d/components/data/data_array.py
tidy3d/components/data/monitor_data.py
tidy3d/components/data/sim_data.py
tidy3d/plugins/mode/mode_solver.py

Note, the way this would work is:
1. `ModeSolver.data` (or `.solve()`) returns a `ModeSolverData` object with symmetry applied (`extend=False`)
2. `SimulationData[mode_solver_monitor_name]` returns a `ModeSolverData` object with symmetry applied (`extend=True`)
The backend then just uses 1. instead of doing things with `SimulationData`, which ends up complicating things a bit because of some monitor naming conflict (`MODE_MONITOR_NAME` conflicted with an existing monitor named 'mode' in the sim_data).

reverts way symmetry is applied to mode solver

---

tidy3d/components/base.py
tidy3d/components/boundary.py
tidy3d/components/data/README.md
tidy3d/components/data/monitor_data.py
tidy3d/components/grid/grid_spec.py
tidy3d/components/viz.py
tidy3d/plugins/webplots/data.py

Before, when type annotating a class method, could not reference the class name. Instead, we put it in quotes:
```py
class MyClass:
def copy(self) -> 'MyClass':
pass
```
In python 3.7 +, we can use the class name in the annotations by importing
```py
from __future__ import annotations
class MyClass:
def copy(self) -> MyClass:
pass
```
note, breaks python 3.6. Are we even supporting it though?

enable self type annotation

---

tidy3d/components/simulation.py

If element in sources is incorrect, the `values` does not have key `sources`, so it will throw `KeyError` exception. It will block the correct pydantic ValidationError throw.

fix throw KeyError exception when sources element is not correct

---

requirements/dev.txt
tests/test_data_performance.py
tidy3d/components/base.py
tidy3d/components/data/data_array.py

For a `SimulationData.hdf5` file of size 4GB on disk:
* Requires 4.21 GB of memory to read and write(using `memory_profiler` python package).
* 11 sec of load time on my machine, few seconds to write.

performance improvements for saving / loading .hdf5

---

MANIFEST.in
requirements/basic.txt
requirements/core.txt
requirements/plugins.txt
requirements/web.txt
setup.py
tests/test_config.py
tidy3d/__init__.py
tidy3d/config.py

- Removed plugins from tidy3d init so importing tidy3d now does not require dependencies for web or plugins
- Instead of removing `config` from tidy3d init, I decided to just remove the web stuff from `tidy3d.config`. The whole web config is a bit hacky anyway, but if we want to keep the code I removed, we should just move it in `tidy3d.web.config`. 
- Added a `basic` requirements file. This together with the fixed init means that you can construct models and load and save data without the need for the web or plugins dependencies. The `tidy3d[basic]` install can probably be used in all of our services that need tidy3d frontend, and make for a smaller build and smaller overhead in tidy3d import.
- The `core` requirements are currently unchanged.
This fixes #441 in that if a user gets the …

Rearranging requirements and removing plugins from tidy3d init

---

simulation.json
tests/_test_web.py
tests/sims/simulation_1_6_0.json
tests/test_data_arrays.py
tests/test_data_monitor.py
tests/test_data_sim.py
tidy3d/components/data/README.md
tidy3d/components/data/monitor_data.py
tidy3d/components/data/sim_data.py
tidy3d/components/simulation.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/version.py
tidy3d/web/container.py
tidy3d/web/webapi.py

`SimulationData` is now such that the normalization (still corresponding to the recorded `normalize_index`) is incorporated in the stored data. A new `renormalize` method is introduced to create a copy of the `SimulationData` with a different normalization. 
This has the following benefits:
- Avoids the confusion users may have of why the data in the hdf5 file is different from the data in python. There will always be a one-to-one match. 
- On the backend, we will use normalize_index = 0 by default. This is what the user downloads, and also can directly be used for post-run viz. Then the user can use the `renormalize` method if they want to remove the normalization (`renormalize(normalize_index=None)`) or pick a different source.
- Together with a change I made for …

Refactor SimulationData normalization once again

---

requirements/core.txt
requirements/plugins.txt
setup.py
tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/dispersion/fit_web.py

In an attempt to remove `nlopt` from requirements, this PR replaces `nlopt` with the `scipy.optimize.minimize` from scipy. 
It needs a 2nd pair of eyes on it to make sure I set up the constriaints and various parameters correctly, could you take a look Weiliang?
When running the dispersion fitter tests in `test/plugins`, I get similar (but slightly worse) final results:
with nlopt
```
_________________________________ test_dispersion _________________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 3.20e-01 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under …
```

Replaced nlopt with scipy in dispersion fitter

---

tests/test_IO.py
tests/test_data_sim.py
tidy3d/components/base.py
tidy3d/components/data/data_array.py
tidy3d/web/s3utils.py
tidy3d/web/webapi.py

This PR takes some elements from #466 but writes all extra data to a single user-supplied file, if provided. So e.g.
```
simulation.to_file("simulation.json", data_file="extra_data.hdf5")
```
would replace all `DataArray` fields in `simulation.json` with a dictionary of the form 
```
{
"group_name": "7c4c4b745fa80d7bc802f944fce2d14b",
"data_file": "extra_data.hdf5",
"tag": "DATA_ITEM"
}
```
and the data will be written to the listed group name in the data file.
I also introduced the webapi change to upload the extra file, if needed.

Splitting simulation file into json + extra data for submitting to server

---

tidy3d/components/grid/grid.py

The `tight` optional argument was added to `discretize_inds` to help with monitor snapping for server-side near-to-far, but is no longer needed. Since it's not used or needed anywhere else, it has been removed.

Removed the tight option for discretizing components 

---

tidy3d/components/geometry.py

Calculation of volumes and surface areas (not always exact) for geometric primitives needed for better memory (see https://github.com/flexcompute/tidy3d-core/pull/130)

volume and surface areas for geometric primitives

---

tests/test_data_sim.py
tidy3d/components/data/sim_data.py
tidy3d/components/grid/grid.py
tidy3d/components/simulation.py

also fix to grid.discretize_inds to not error if the box is out of the simulation bounds

Fix to zero-dim monitor when applying symmetry

---

tests/test_IO.py
tidy3d/components/base.py

if `value` is `None` when packing dataset, save as `np.nan`. If `np.nan` encountered in `hdf5` file, load as `None`.

save and load None in hdf5 files

---

tests/sims/simulation_1_6_2.json
tests/test_IO.py
tidy3d/components/base.py

Both hdf5 and json should have it now.

added type field to dataarray in file

---

tests/sims/simulation_1_6_3.json
tidy3d/components/base.py

It turns out that by default pydantic passes copies of models to other models and when doing vaidations. This creates a lot of overhead in the case of e.g. many structures. I believe it is ok to turn this off since everything is static for us.

Setting pydantic copy on validation to false

---

tests/sims/simulation_1_6_1.json
tests/sims/simulation_1_7_0.json
tests/test_IO.py
tidy3d/components/README.md
tidy3d/components/simulation.py
tidy3d/updater.py
tidy3d/version.py

This should be done only in the next major release, and we should add the `"grid_size"` removal in the updater for version 1.6 to latest update. This is because e.g. 1.6.2 files still have `"grid_size": None` so if I try to load such a json in 1.6.3 with `grid_size` removed as a Field, it errors.

remove grid_size

---

tidy3d/components/base.py

new way to set this config was introduced in pydantic 1.10. Without this change, will get a DeprecationWarning.

fixed deprecation warning with new copy_on_validation 

---

tests/sims/simulation_1_7_1.json
tidy3d/components/data/monitor_data.py
tidy3d/components/monitor.py
tidy3d/version.py

- Diffraction monitor stores a `Medium` as a field
- Diffraction computations take this medium into account
Backend PR: https://github.com/flexcompute/tidy3d-core/pull/168

User-specified medium for diffraction

---

tests/test_components/test_sidewall.py
tidy3d/components/geometry.py

Polyslab: test coverage and fix an intersection plot issue

---

tests/test_components/test_source.py
tidy3d/components/source.py

frontend part of broadband sources

broadband source feature

---

tests/test_data/test_monitor_data.py
tidy3d/components/data/monitor_data.py

With this change, we can do e.g. `mode_data.dot(other_mode_data)` for frequency / mode index coords that do not match, if the supplied `other_mode_data` has a single element along these dimensions. The coords of the original data are preserved. This is because you don't necessarily always want to do the dot product for modes at exactly the same frequency or with exactly the same mode ordering.

Broader broadcasting in FieldData.dot

---

tidy3d/components/simulation.py

All backend tests pass, just a few of them needed a small increase in the tolerances, but everything looks good and this should make the time stepping 10% faster.

Bumping default courant factor to 0.99

---

tests/test_components/test_sidewall.py
tidy3d/components/geometry.py

- `sidewall_angle` etc. has been shifted to `Planar`.

Cylinder with sidewall angle

---

tidy3d/components/simulation.py

Hi @tylerflex this small fix gets rid of the warning when one of the plot dimension's size is zero. I tested on a bunch of 1D, 2D, and 3D examples and it doesn't seem to affect any plotting functions so far. Do you see any potential adversarial effect it could have?

Avoid setting axis limits if lower and upper limits are equal

---

tests/test_components/test_source.py
tidy3d/components/source.py

Since the backend broadband source feature is more robust now I wonder if we should make the frequency range a user defined parameter?

Shrink frequency range for broadband sources to +/- 1.5 * fwidth

---

tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/dispersion/fit_web.py

- Lower pole frequency bound for stable simulation when the dispersive medium is extended into PML.
- Freezing seeds in the fitter by default so that one obtains identical results when simply re-running the fitter.
- ignore k data option in `from_url` since sometimes the medium is in fact lossless but the URL provides data with small k at different wavelengths, e.g. https://refractiveindex.info/data_csv.php?datafile=data/glass/schott/N-BK7.yml
(the web-service is to be deployed, so it's not functional yet.)

Lower frequency bound and freezing seeds in fitter

---

tests/test_components/test_custom.py
tidy3d/components/data/data_array.py

Fixes KeyError for ScalarFieldDataArray not hashable if custom medium is added to Simulation.structures

adds `__hash__` to DataArray

---

tidy3d/components/data/monitor_data.py

instead of `self.coord_name` eg. `self.Etheta.f`
This makes it a tiny bit more general for subclasses of `DiffractionData` and therefore easier for the adjoint plugin to work properly.
No rush to merge this, can be done after 1.8. Just simplifies a bit in the adjoint plugin and shouldn't affect anything else.

coordinate properties in DiffractionData use `coords["coord_name"]`

---

tests/test_components/test_geometry.py
tests/test_components/test_grid.py
tests/test_data/test_data_arrays.py
tests/test_data/test_monitor_data.py
tests/test_data/test_sim_data.py
tidy3d/components/data/data_array.py
tidy3d/components/data/dataset.py
tidy3d/components/data/monitor_data.py
tidy3d/components/field_projection.py
tidy3d/components/geometry.py
tidy3d/components/grid/grid.py
tidy3d/components/monitor.py
tidy3d/components/simulation.py
tidy3d/log.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/web/webapi.py

The fundamental issue that this PR addresses is the following. Say you have a primal grid along `z` defined on `n dz` and a dual grid defined on `(n + 0.5) dz`. Say also that you have a perfectly injected mode propagating along z, such that the frequency-domain tangential fields on the primal grid are exactly given by some `E0 exp(1j * k * n * dz)`, `H0 exp(1j * k * (n + 0.5) * dz)`, where k is the effective wave vector of the mode at a particular frequency. Now, if you pick an arbitrary position `z` along the propagation direction, and use linear interpolation to compute `E(z)` and `H(z)`, and then use those to compute the flux at that location, you will get values that *oscillate* with `z` weakly but non-negligibly.
So far, to hide this from the user, we have been normalizing the …

Updates to make user-side flux (and near2far) computation consistent

---

tests/test_web/test_webapi.py
tidy3d/web/config.py
tidy3d/web/httputils.py

Added environment name TIDY3D_SSL_VERIFY checking.
Default value is True.
When user ``export TIDY3D_SSL_VERIFY=false``, it will skip certification verify.
Please note that the name is TIDY3D_SSL_VERIFY, instead of TIDY3d_DISABLE_SSL which is used in hotfix branch.

add ssl verify

---

tests/test_components/test_boundaries.py
tests/test_components/test_geometry.py
tidy3d/components/boundary.py
tidy3d/components/geometry.py

`log.warning()` if
* `Boundary.plus` or `Boundary.minus` not defined
* `reference_plane` not supplied but `sidewall_angle` is non-zero

deprecation warnings for API updates in 2.0

---

poetry.lock
pyproject.toml
tidy3d/version.py
tidy3d/web/cli/readme.md

Hi @An-Li-magicloud 
I did a bit of work on trying to get this working with test PyPI. 
I had to modify the `pyproject.toml` a bit.
Now it seems like the dependencies are conflicting when I try to pip install from test.pyPI.
I put my process in the `tidy3d/web/cli/README.md` and sent you my token separately.

poetry publish works with test.PyPI

---

requirements/basic.txt
tidy3d/__init__.py
tidy3d/components/grid/mesher.py

Fixes https://github.com/flexcompute/tidy3d/issues/642 , apart from for python 3.7, for which I experienced a problem building shapely 2.0 on one of our workers. It does not seem to be a general python 3.7 thing, but shapely 1.8.0 builds well on that worker.
I am not sure if this should be put in 1.8.2 or 1.9.0.

Bumping shapely version to 2.0

---

tests/test_package/test_log.py
tidy3d/log.py

Previously `self` was being passed to `Exception.__init__` instead of the exception message in the Tidy3dException and other subclasses. This was causing the resulting exception to store `str(self)` as the "message" and causing issues in formatting.

fix tidy3d exception subclasses

---

tidy3d/material_library/material_library.py
tidy3d/material_library/material_reference.py

Added a `Olmon2012Drude` option for gold and a `Yang2015Drude` option for silver to the material library. The poles are obtained by converting the Drude model so the number of poles is much smaller compared to other options of gold and silver in the library.
These options are mainly targeted towards lower frequency in mid to far IR. The data frequency range is 0.05eV (12 THz) to 1 eV (240 THz) although I think it can be safely used all the way to even below 1 THz. According to the data from the referenced papers, Drude model works well up to 1 eV and starts to show discrepancy above 1 eV. 
The attached notebook tested the added options. The plotted permittivity is in agreement with the data from the referenced papers.
[MaterialLibraryTesting.zip](https://github.com/flexcompute/tidy3d/files …

Added Drude model options for gold and silver

---

tests/test_components/test_custom.py
tests/test_components/test_geometry.py
tests/test_components/test_medium.py
tests/test_plugins/test_mode_solver.py
tidy3d/__init__.py
tidy3d/components/data/data_array.py
tidy3d/components/geometry.py
tidy3d/components/medium.py
tidy3d/components/simulation.py
tidy3d/components/structure.py
tidy3d/components/types.py
tidy3d/components/viz.py

Incorporate changes from #498 with the new data refactor in mind.
A few things of note:
* `CustomMedium.from_eps_raw()`allows user to construct each of the `eps_ii` data arrays from a single data array. How do we handle this on the backend? Do we want to change this behavior or add a new class method constructor, for example, for supplying eps at the center only?
* All of the medium `.eps_model()` take `frequency` argument, maybe we can change to `f` instead to be consistent with the data coordinates?
Needs backend implementation.

add custom medium

---

tests/test_components/test_sidewall.py
tests/test_plugins/test_polyslab.py
tidy3d/components/geometry.py
tidy3d/plugins/__init__.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/polyslab/__init__.py
tidy3d/plugins/polyslab/polyslab.py

The support of self-intersecting polyslabs is scheduled to roll out in two phases. In phase 1, we consider the case where the length of some edges can approach 0 (or neighboring vertices become degenerate) at some point during extrusion. In phase 2, more general types of edge events will be treated. The main idea in this PR is to divide a complex polyslab into many simple polyslabs.
-  A class `ComplexPolySlab` is defined in plugin. It takes the same fields as `PolySlab`. We can consider move this class to `geometry.py`. The current design is to leave space for phase 2.
- An example on how to use this class can be found [here](https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/weiliang/self-intersecting/docs/source/notebooks/SI_example.ipynb). In short, one can use the property …

Phase 1: self-intersecting polyslab

---

.pre-commit-config.yaml
pyproject.toml
requirements/basic.txt

If you make a commit and black can make formatting changes, the changes are made and the commit isn't registered. Should avoid any commits where black is not applied.
```
pip install pre-commit
pre-commit install
```
I also needed
```
pre-commit run --all-files
```
before it started working.
[see this guide](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) for more info.

add pre-commit hook for black

---

MANIFEST.in
requirements/dev.txt
requirements/gdspy.txt
requirements/gdstk.txt
setup.py
tests/test_components/test_geometry.py
tidy3d/components/geometry.py
tox.ini

And add gdspy and gdstk as optional requirements.
@lucas-flexcompute 
Just took a stab at this using (perhaps an abuse of) `try: except:`, but let me know if you think there's a better way to handle it.
I also notice that neither `gdstk` nor `gdspy` are actually required for these to work as they aren't imported in the main package. The user just supplies a `Cell` from either package. In that case, do we need them as optional requirements at all?

Try gdspy vertices loading if gdstk loading fails

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/components/simulation.py

Warn if a 2D simulation uses an absorbing boundary in the zero dimension. Eventually we may want to automatically switch to a periodic boundary.
Not urgent; we can merge this later on after discussing further.

2D simulation boundary warning

---

tests/test_components/test_boundaries.py
tests/test_components/test_custom.py
tests/test_components/test_geometry.py
tests/test_components/test_simulation.py
tests/test_data/test_monitor_data.py
tests/test_plugins/test_adjoint.py
tests/test_plugins/test_polyslab.py
tests/utils.py

Makes it more intuitive and easier to write tests that we want to warn, log, etc.

assert_log_level takes level string instead of int

---

.pylintrc
CHANGELOG.md
tests/test_components/test_geometry.py
tests/test_components/test_simulation.py
tidy3d/components/geometry.py
tidy3d/components/simulation.py

The two main updates are:
- `geometry.intersects_plane` is now much faster. Before, it would call `geometry.intersections`, which can be slow. Now, instead, `intersects_plane` is fast, and is used to speed up `geometry.intersections` in some cases by doing a quick check if the plane is out of bounds.
- `geometry.inside_meshgrid` method introduced to speed up `geometry.inside` computations that are defined on a regular grid in `x, y, z` (as in `sim.epsilon`). With these improvements, for example getting the epsilon in a region with 28k spheres takes just 5s (4s if they are defined as a GeometryGroup).
I would say this fixes #668 for now.

Reorganize geometry.inside and intersection methods for some speed improvements

---

CHANGELOG.md
requirements/basic.txt
tests/_test_local/_test_web.py
tests/test_plugins/test_adjoint.py
tests/utils.py
tidy3d/components/data/monitor_data.py
tidy3d/plugins/adjoint/__init__.py
tidy3d/plugins/adjoint/components/data/monitor_data.py
tidy3d/plugins/adjoint/web.py
tidy3d/web/queue.py

Introduces a new function into the adjoint webapi called `async_run`, which accepts a tuple of `JaxSimulation` objects and runs them asynchronously using the `tidy3d.web.async_run` function.
This enables functions like:
```py
def objective(x) -> float
"""A multi-frequency objective."""
sims = [make_sim(x, freq) for freq in freqs]
sim_datas = async_run(sims)
return jnp.sum([post_process(sim_data) for sim_data in sim_datas])
```
to be differentiated.
Note, this PR changes the behavior of the `web.run_async` function introduced in #702 as it makes this function no longer asynchronous to the user, meaning they can use as normal without needing to `await` the result.

multi-objective adjoint through `adjoint.async_run`

---

CHANGELOG.md
tidy3d/plugins/mode/solver.py

I was getting a lot of divide by zero warnings in the `np.linalg.det` calls from the mode solver.
Digging into the issue, I found it was because taking a determinant of a complex-valued identity matrix triggers this warning, which was the case for the jacobians in the mode solver that were being passed to `np.linalg.det`.
```py
import numpy as np
arr = np.eye(3) + 0j
np.linalg.det(arr)
```
```
/Users/twhughes/.pyenv/versions/3.10.9/lib/python3.10/site-packages/numpy/linalg/linalg.py:2139: RuntimeWarning: divide by zero encountered in det
r = _umath_linalg.det(a, signature=signature)
/Users/twhughes/.pyenv/versions/3.10.9/lib/python3.10/site-packages/numpy/linalg/linalg.py:2139: RuntimeWarning: invalid value encountered in det
```
To fix this, I casted the jacobians to`np.real`. …

fix determinant warning

---

CHANGELOG.md
tidy3d/components/geometry.py
tidy3d/components/monitor.py
tidy3d/components/source.py
tidy3d/components/viz.py

Curved arrows are only possible through FancyArrowPatch, but those define the arrow head size in display coordinates and end points in data coordinates.  Furthermore, the arrow head is included in the total length, as opposed to what happens with Axes.arrow, that was used before.  The result is that the arrow length calculated based on the axes limits or simulation boundaries can end up too small for the arrow head (and for visualization as well).
The solution here, which might actually be preferable even without the bending, is to define the arrow size in real units (inches, following matplotlib's DPI setting) so that the arrows are always the same size. That can only be accomplished by waiting for the transformations to be set, at drawing time, so we use a `draw_event` callback to …

Add arrow curvature to sources and monitors with bend radius (#272)

---

tidy3d/constants.py

The speed of light in vacuum has an exactly defined value, whereas the vacuum permittivity and permeability are measured to a certain precision.  It is usual to use the exact value of the speed of light and the permeability to calculate the permittivity.
(This is very minor, but I felt like changing to be more accurate, since I was looking into the inner works of the mode solver.)

Small conceptual change to constants definitions

---

MANIFEST.in
requirements/dev.txt
requirements/surfacemesh.txt
setup.py
tests/data/tetrahedron.stl
tests/sims/simulation_1_9_0.json
tests/sims/simulation_1_9_0rc2.json
tests/test_components/test_IO.py
tests/test_components/test_geometry.py
tests/utils.py
tidy3d/__init__.py
tidy3d/components/data/data_array.py
tidy3d/components/data/dataset.py
tidy3d/components/geometry.py
tidy3d/components/simulation.py
tox.ini

Features:
- `CustomSurfaceMeshGeometry` class
- Import from and export to STL (uses trimesh library)
- `SurfaceMeshDataArray` class handling HDF5 packaging of STL data
- Plotting simulations containing custom surface mesh geometry
- Validate STL mesh as watertight, consistent winding, and nonzero face area
Limitations:
- The plotting and epsilon on frontend is only self-consistent if the mesh is unionized. The backend should handle non-unionized meshes correctly. We can't check whether a mesh is unionized, so we just give a warning when plot or epsilon are called.
- Volume and surface area calculation ignores bounds
- Volume and surface area can overcount for non-unionized meshes.

STL Import

---

CHANGELOG.md
tidy3d/material_library/material_library.py

Requested by @jwang-magicloud to include material name info with a specific format in the generated json file.

Include material name in material_library's export_matlib_to_file

---

tests/test_web/test_tidy3d_task.py
tests/test_web/test_webapi.py
tidy3d/web/container.py
tidy3d/web/simulation_task.py
tidy3d/web/webapi.py

task name should be fixed now. 
Solver version can be passed to `web.run()` or directly to `web.start()`

fix task name and expose solver version

---

tidy3d/components/types.py
tidy3d/plugins/mode/solver.py

All functions in solver.py have been converted into static method. The contents of the functions are untouched.

Convert mode solver.py into a class

---

tidy3d/components/medium.py

Fix a backend test failure because sometimes `dt` becomes a dataarray rather than a float.

Ensure n_cfl is float for custom medium

---

tests/test_plugins/test_adjoint.py

As @caseyflex pointed out (and I verified), this test was failing with some mysterious SSLError. I found that it only happens when the tests are run with `pytest tests`, but seems to pass when the tests are run individually, eg `pytest tests/test_plugins/test_adjoint`. For now I think it's ok to just remove the test to avoid issues down the line.

remove a broken adjoint test

---

tidy3d/components/geometry.py

Without a grid size, the default from shapely is `double` precision, which leads to artifacts in the final geometry.  Because the GDSII cordinates are already snapped to a grid, this should have no adverse effect unless the GDSII grid is finer than 1e-12.  The usual default in GDSII files is for precision to be 1e-9 with unit 1e-6, that is a grid size of 1e-3, so the chosen value of 1e-12 should be quite safe.

Set grid size for union of GDSII shapes

---

CHANGELOG.md
tests/test_data/test_sim_data.py
tidy3d/components/data/README.md
tidy3d/components/data/sim_data.py
tidy3d/components/types.py
tidy3d/plugins/mode/mode_solver.py

- Allow plotting the Poynting vector from `SimulationData.field_plot` and full vectorial magnitudes for E and H.
- Include components `"abs^2"` and `"dB"` to `val`, applicable to all components.
- Improve the selection of divergent colormap whenever the data _could_ contain positive and negative values, and centralize map around zero.

Extra field plot options

---

tests/test_web/test_cli.py
tidy3d/web/__init__.py
tidy3d/web/cli/app.py
tidy3d/web/cli/constants.py
tidy3d/web/cli/migrate.py
tidy3d/web/httputils.py

add migrate function and migration cli for user who has auth.json file.
It will asked user to migration from credential to API Key

add auth.json migration to API key

---

CHANGELOG.md
tests/test_components/test_types.py
tidy3d/components/apodization.py
tidy3d/components/base.py
tidy3d/components/data/monitor_data.py
tidy3d/components/field_projection.py
tidy3d/components/geometry.py
tidy3d/components/grid/grid.py
tidy3d/components/grid/mesher.py
tidy3d/components/medium.py
tidy3d/components/monitor.py
tidy3d/components/source.py
tidy3d/components/types.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/resonance/resonance.py

`ArrayLike` converts provided value into `np.array` and is encoded to json using `tolist()` for real and imaginary parts separately.
`constrained_array(dtype, ndim)` returns an `ArrayLike` with the dtype and number of dimensions either cast or validated.

revamped ArrayLike

---

CHANGELOG.md
tests/test_components/test_grid_spec.py
tests/test_components/test_medium.py
tests/test_components/test_simulation.py
tests/test_package/test_material_library.py
tests/test_package/test_parametric_variants.py
tidy3d/__init__.py
tidy3d/components/geometry.py
tidy3d/components/grid/grid_spec.py
tidy3d/components/grid/mesher.py
tidy3d/components/medium.py
tidy3d/components/monitor.py
tidy3d/components/simulation.py
tidy3d/components/structure.py
tidy3d/constants.py
tidy3d/material_library/material_library.py
tidy3d/material_library/material_reference.py
tidy3d/material_library/parametric_materials.py

Features:
- `Medium2D` class for surface conductivity model of 2D material
- Material library entries for graphene and some common TMDs
- Ability to create a 2D representation of a thin 3D metal
- AutoGrid for 2D materials.
Todo:
Plan for autogrid:
- Place a grid boundary at the 2d material
- Mesh the normal direction ignoring the 2d material
- Then mesh the in-plane directions using the volumetric equivalent
Limitations:
- Autogrid will not support non-parallel 2d materials
- Won't allow multiple 2d materials with separation smaller than the minimum grid size
- Does not support non-homogeneous neighboring materials above and below the 2d material. So, for example, you might need to manually divide a 2D material into multiple pieces, one for each substrate medium.

2D Materials

---

tidy3d/components/simulation.py

the new post-init validator I introduced had a bug causing it to mistake where it thought the edge of the PML was.
This PR fixes the validator and also removes a warning in the simulation.py docstring test, which was causing it to fail.
Note: some of the docstrings still fail because they print warning / info messages, but they should be fixed for 2.0 when we make the default level WARNING and remove deprecation warnings in the boundary spec.

fix pml validator

---

CHANGELOG.md
tests/test_components/test_geometry.py
tests/test_components/test_sidewall.py
tidy3d/components/geometry.py

For a slanted cylinder of infinite length, the reference plane can only lie in the middle. Otherwise, the behavior of cylinder at the `center` is confusing. A validator has been added.
Additionally, when `self.length_axis` is td.inf, internally in cylinder, we use `LARGE_NUMBER` instead. This is to make sure for a slanted cylinder, `radius_max` etc. are well defined. 
Finally, override the `radius` attribute in cylinder to clarify where the radius is defined.

Treat infinite slanted cylinder and add validators

---

tidy3d/components/geometry.py
tidy3d/components/medium.py
tidy3d/material_library/parametric_materials.py

Fixes graphene docstring, and makes the errors for importing trimesh and scipy more helpful. Also adds frequency_range to various methods around Medium2D.

Minor fixes to docstrings and import error messages

---

tests/sims/simulation_1_10_0.json
tidy3d/components/geometry.py

The import exception handling can fail if an exception different from an `ImportError` is raised while importing a package.

Broad except when importing trimesh and rtree

---

CHANGELOG.md
requirements/basic.txt

Backend tests pass with this. Did you want to wait until after 2.0 though @tylerflex ?

Unpinning importlib-metadata version

---

CHANGELOG.md
tidy3d/web/webapi.py

For some reason, the run info webapi seems to have started returning: 
perc_done = 0
field_decay = 0
early in the task. (maybe before the solver progress csv is ready).
As a result, the condition for printing the early shutoff warning:
```py
if perc_done is not None and perc_done < 100:
```
was being triggered even if the task was finishing without early shutoff.
This PR changes to only trigger if 
```py
if perc_done is not None and perc_done < 100 and field_decay > 0:
```
basically if the solver progress is not present and the task has stopped running, it doesn't print this log message anymore. We should follow up with MC though.

extra condition before printing early shutoff log

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/components/simulation.py

Makes the PML boxes (for plotting) have a size of `0.02` along any dimensions where sim.size == 0.
Otherwise, there are times where the PML will not show, eg plotting a simulation with size (1, 1, 0) along the z axis, because the PML has a size of 0 along z and the box does not get picked up by the plotter.
note, used a small number instead of td.inf to avoid potential weirdness in the 3D or cross section plots.
Also, the plotting wasn't picking up any number smaller than 0.02..
Before:
After:

add finite extent to PML for dims where simulation.size == 0

---

tidy3d/plugins/waveguide/rectangular_dielectric.py

Minor fix for waveguide plugin: actually return the axis from the plot wrapper functions.

Return axes from plot wrappers

---

CHANGELOG.md
README.md
tidy3d/web/__init__.py
tidy3d/web/cli/app.py

In a hosted jupyter notebook environment (eg google colab), it may be more convenient to install and configure via the following lines at the top of the notebook.
```
!pip install tidy3d
import tidy3d.web as web
web.configure("XXX")
```
note, README is updated to include these instructions as well as the Quickstart in the docs.

add python function `web.configure(apikey)` to configure

---

tidy3d/components/base.py

fixes https://github.com/flexcompute-readthedocs/tidy3d-docs/issues/183

fix typo in `from_hdf5` docstring example

---

tests/test_plugins/test_adjoint.py
tests/utils.py
tidy3d/plugins/adjoint/web.py

I managed to get a first iteration working on the backend. We need a few modifications on the frontend, I started working on those here. I think they all revolve around making everything communicate through files instead of keeping things in memory as it was set up. @tylerflex could you help with the refactor?
Some things to think about:
- Writing and reading JaxInfo to file.
- Ideally no simulation-related data should be read from the web response. This should only be used for metadata, status, etc. I have refactored things to write SimulationData to file in the tests, and then read it in, to emulate how it will actually work. For this I had to work with SimulationData and not JaxSimulationData, as writing this to hdf5 and then reading it back in caused jax to error.
- There seems to be …

Refactoring functions to communicate through files

---

CHANGELOG.md
tidy3d/log.py

Fix for logging the correct calling site.
For example, before this patch:
```sh
$ python -c 'import tidy3d; tidy3d.log.warning("Warning test"); raise tidy3d.exceptions.Tidy3dError("Error test")'
[15:53:47] WARNING: Warning test                                                                                                                                                                           log.py:50
ERROR: Error test                                                                                                                                                                               log.py:50
Traceback (most recent call last):
File "<string>", line 1, in <module>
tidy3d.exceptions.Tidy3dError: Error test
```
After the patch:
```sh
$ python -c 'import tidy3d; …
```

Find stack offset to log correct calling site

---

CHANGELOG.md
tidy3d/web/webapi.py

Short term attempt at making the webapi more stable in connection outages.
For all major webapi functions, if connection errors, logs a warning once and retries connection for CONNECTION_RETRY_TIME=30 seconds (with REFRESH_TIME period in between tries). 
Note, not applied to `web.monitor` as this function wraps other webapi functions so it is already covered and adding it at top level would cause the warning to trigger twice.

retry connection in web functions

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/components/simulation.py

See https://github.com/flexcompute/tidy3d/issues/875

Remove Medium2D as allowed for Simulation.medium in docs

---

CHANGELOG.md
tests/sims/simulation_2_2_0.json
tests/test_components/test_simulation.py
tidy3d/components/data/sim_data.py
tidy3d/components/simulation.py
tidy3d/components/source.py

Reported in https://flow360.atlassian.net/browse/SCEM-2316
Ideally, I think we should update `amp_time`, but it will require changes in backend as well. So I simply fix it inside the plot function.

Fix source amplitude in spectrum and source-time plotting

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/web.py

Enables adjoint processing to be done client side, for debugging, development, and as a backup in case something breaks

add `run_local` and `run_async_local` options to adjoint plugin

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/components/geometry.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/medium.py

In the adjoint vjp timing test, this reduces the run time for 1000 vertices from 120s to 14s on my machine.
To-dos:

Parallelizing polyslab vjp, and using matplotlib.path.contains_points in PolySlab.inside

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/components/simulation.py

Fixes #873 .
@tomflexcompute actually you were right, I thought that the current limit was per monitor but it was actually for the full simulation. I made the modifications as we discussed and made user messages show things in GB which I think makes more sense.

Bumping maximum allowed projected data size to 50GB

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tests/utils.py
tidy3d/components/geometry.py
tidy3d/plugins/adjoint/__init__.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/medium.py
tidy3d/plugins/adjoint/components/simulation.py
tidy3d/plugins/adjoint/components/structure.py

Introduces 
* `JaxPolySlab` geometry that can track gradients through its `.vertices`.
* `JaxStructure` with `JaxPolySlab` geometries can accurately track gradients through its medium using `inside()` to mask the volume integration.
Limitations:
* Gradients will be inaccurate if the `JaxPolySlab` immediate background is inhomogeneous (validator to warn)
* `.slab_bounds` not supported but coming soon.

Adjoint PolySlab

---

CHANGELOG.md
tests/test_components/test_medium.py
tests/test_components/test_meshgenerate.py
tests/test_components/test_simulation.py
tests/test_components/test_types.py
tests/test_plugins/test_mode_solver.py
tidy3d/__init__.py
tidy3d/components/base.py
tidy3d/components/geometry.py
tidy3d/components/grid/mesher.py
tidy3d/components/medium.py
tidy3d/components/simulation.py
tidy3d/components/structure.py
tidy3d/components/transformation.py
tidy3d/components/types.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/mode/solver.py

Frontend interface for fully anisotropic materials:
- Since `AnisotropicMedium` was already taken, fully anisotropic materials are called `FullyAnisotropicMedium`
- Currently only materials for which main directions of permittivity and conductivity (symmetric part) tensors coincide (to have well-defined main complex permittivities)
- A helper class `RotationAroundAxis(AbstractRotation)` is implemented for convenient rotation of tensors in space. In future we can add more methods like `RotationEulerAngles(AbstractRotation)`, etc.
- Automatic mesher now takes into account only the max eps among all directions (previous treatment based on normal direction resulted in underresolving because tangential direction define wavelength)
- For now injection of plane waves and gaussian beams into …

Fully anisotropic materials

---

CHANGELOG.md
tidy3d/plugins/mode/solver.py

Fixed a very silly bug in the recent mode solver improvements which was causing the preconditioner to always be applied.

Fix syntax bug in mode solver

---

CHANGELOG.md
tidy3d/components/simulation.py

Ignore TFSF surfaces outside the simulation domain in the intersections validator.

Out-of-bounds TFSF surfaces

---

CHANGELOG.md
tests/test_components/test_custom.py
tidy3d/components/base.py

Fixes the IO issue by adding a special handling for nested lists containing DataArray. Turns out the recursive algorithm wasn't handling this case properly and it wasn't really caught because we didn't have any instances like this to worry about until now.

fix custom dispersive medium IO with nested data arrays

---

CHANGELOG.md
tests/test_plugins/test_dispersion_fitter.py
tidy3d/plugins/dispersion/__init__.py
tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/dispersion/fit_web.py
tidy3d/plugins/dispersion/web.py

The API for dispersion fitting is a single call, so there's not much to monitor. I've basically moved things around to mimic the `web.run` interface from other plugins.

Unify dispersion fitters with a web.run interface

---

tidy3d/components/geometry.py

Fixes plotting of large circular patches
Before:
After:

More segmets in shapely circular patches discretization

---

tidy3d/plugins/adjoint/web.py

The adjoint web functions can time out on e.g. upload of the jax info, or download of the sim_vjp. This is one way to fix it - another one would be to add the decorator to some of the base tidy3d.web.s3utils functions like upload_file and download_file.

Retry connection in adjiont web functions

---

CHANGELOG.md
tests/test_components/test_custom.py
tidy3d/components/grid/grid.py
tidy3d/components/medium.py

That way it can be used by custom current sources.

Move `CustomMedium._interp` to `Coords.spatial_interp`

---

tidy3d/material_library/material_library.py

For some reason (probably the refractiveindex.io decided to change their URL somehow) the data links in the material library doc page are all broken. Please see https://docs.flexcompute.com/projects/tidy3d/en/latest/material_library.html. 
This PR updated the links and resolved the issue https://github.com/flexcompute/tidy3d/issues/913

Fixed broken links in material library

---

CHANGELOG.md
tests/test_data/test_monitor_data.py
tidy3d/components/data/monitor_data.py

Skip selection by mode_index when it doesn't exist in the input and remove it from the output.

Fix overlap calculation for FieldData (#423)

---

CHANGELOG.md
tests/sims/simulation_2_3_0rc1.json
tests/test_plugins/test_mode_solver.py
tidy3d/plugins/mode/derivatives.py

Something was slightly off in the pml profiles set in the mode solver. I have updated them to what seems correct to me and added a test. This improved a lot the non-orthogonality for modes that have strong component in the PML as discussed [here](https://github.com/flexcompute/tidy3d/issues/423#issuecomment-1586016544). Also it improved the modes when the underlying structure is effectively symmetric, without a symmetry being explicitly defined.

Fixing pml profiles in mode solver

---

CHANGELOG.md
tests/test_web/test_webapi.py
tidy3d/web/container.py

I noticed that the `estimate_cost()` was looking for "flex_unit" in the task info dict, which was None. I changed it to `estFlexUnit` to fix things.
Note: it seems that when the estimated cost is not available, it gets returned as 0, which is potentially confusing. Should we return `None` in this case?
another note: if the job has not started, it seems like the estimated credits are never available. Is that supposed to be the way it works?

add estimate_cost() method to Job and Batch

---

tests/sims/simulation_2_3_0rc2.json
tidy3d/plugins/dispersion/web.py

we merged some [changes](https://github.com/flexcompute/tidy3d/pull/952) into develop that consolidated the webAPI config. When we merged these changes into pre/2.3, the web fitter was out of date. I tried to fix it but could you both 
(an) take a look and make sure this is the right fix and (Lucas) test it? 
Thanks!

fix dispersion fitter to use consolidated web API config

---

CHANGELOG.md
tests/sims/simulation_2_3_0rc2.json
tests/test_package/test_parametric_variants.py
tidy3d/material_library/parametric_materials.py

- Fixes poor fitting performance under certain parameter choices
- Adds a warning if the fit is not good
- Extends the testing to more physical parameters
- Fixes the error message related to stability of intermediate calculations
- Fixes warnings related to numerical integration
Limitations:
- Fit still can be imperfect, or have a small passivity violation, under certain parameter choices. It is still always stable, so the simulation will still usually be stable.
- Need to check that the bounds on the physical parameters are reasonable @tomflexcompute 
I checked that the graphene notebook is not affected by this.

Improvements to graphene fitter

---

tidy3d/components/monitor.py

Added more detail to the field projection docstrings based on user feedback. Thanks @tomflexcompute for pointing this out.

Field projection docstrings improvement

---

.github/workflows/run_tests.yml

To alleviate missing `bz2` package in github's Mac OS Python3.7 environments.

remove python 3.7 from tested envs

---

CHANGELOG.md
tests/test_package/test_log.py
tests/test_plugins/test_mode_solver.py
tests/test_web/test_webapi.py
tidy3d/components/data/monitor_data.py
tidy3d/components/mode.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/mode/web.py
tidy3d/plugins/waveguide/rectangular_dielectric.py
tidy3d/web/s3utils.py
tidy3d/web/simulation_task.py
tidy3d/web/webapi.py

The local mode solver can be used through `ModeSolver.solve_local`.
This is a WIP because the changes to the current mode solver can be "messy", so everyone's input is welcome.
The cache system had to be extended to allow for caching aliases, because the solve function returns the value of the `data_raw` property, which is cached. Thus `solve_local` must share a cache entry with `data_raw`, which is now possible by passing a name to the cache decorator.

Enable access to remote mode solver from python

---

CHANGELOG.md
tidy3d/components/types.py
tidy3d/schema.json

It was pointed out that fields with `ArrayLike` types had the wrong `title` in the schema. The titles were just saying `ArrayLike`. this PR fixes it, which is verified in the updated schema.json.

fix schema for ArrayLike

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/components/data/dataset.py
tidy3d/components/data/monitor_data.py
tidy3d/components/data/sim_data.py
tidy3d/plugins/adjoint/components/data/data_array.py
tidy3d/plugins/adjoint/components/data/monitor_data.py
tidy3d/plugins/adjoint/components/medium.py

@momchil-flex this is ready for review. I separated the `flux` bits into #968 . This PR allows `interp` and `get_intensity()`.

adjoint differentiable `.interp` support

---

CHANGELOG.md
tests/test_components/test_custom.py
tests/test_components/test_medium.py
tidy3d/components/medium.py

- Applies subpixel to a structure made of custom medium if 1) simulation's subpixel=True; 2) custom medium's subpixel=True
- For CustomAnisotropicMedium, each component has its own subpixel field. E.g. if xx-component has subpixel=True, and yy-component has subpixel=False, subpixel will be applied to xx component but not yy component.

Add subpixel field in custom medium

---

tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/simulation.py
tidy3d/plugins/adjoint/web.py

A few changes:
1. made NUM_PROCS_LOCAL and NUM_PROCS_SERVER for toggling these. Added into tests and default kwargs where appropriate. I think before the tests might have not been triggering the parallel vjp, at least for JaxPolySlab (not sure now) so I did some work to ensure that all pathways were tested depending on whether run_local or run were used in the tests.
2. refactored so that `store_vjp` generally toggles between a `store_local_parallel` and a `store_local_sequential` based on `num_procs`, seemed slightly cleaner (but more verbose) to handle it this way.
3. A bit more refactoring (eg separate function for making args in the jax polyslab VJP).
Let me know what you think and feel free to take any of these changes as you feel necessary.

factor out store_vjp sequential and parallel, fix num_procs passing

---

CHANGELOG.md
tidy3d/web/task.py
tidy3d/web/webapi.py

Now `taskInfo.estFlexUnit` is always used, and changes have been made on the server for a `taskInfo.metadataStatus` to be added. If the web api times out, a dedicated worker picks up the task to ensure that the metadata will eventually be processed.
This only works on dev env currently. Let's merge only once the server changes are in prod.

Estimate cost should now always work

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/components/simulation.py

feel free to change the number, as long as the Metalens Demo supports it.  I think it's currently 18x18 = 324 for the symmetry expanded one and under 100 without symmetry. However, we construct the symmetry expanded one for plotting at the end.. (even though we dont run it). Not really sure how to approach this. maybe a pre-upload validator?  Note, if we go this route, we'll need to somehow ensure that the Simulation.validate_pre_upload() is still called.

restrict number of adjoint input structures

---

tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/simulation.py
tidy3d/plugins/adjoint/components/structure.py
tidy3d/plugins/adjoint/web.py

This is not exactly pretty currently, but I'm not sure how to improve. Have to pass these big args lists around that can be confusing. However, when you work with a parallel pool, you can't directly use values and functions that are in the local namespace.
The other complication is that some structures need to *internally* use multi-processing (PolySlab, GeometryGroup), while others don't do that. So we split the list in two parts, structures where store_vjp is called in serial with num_proc internally, and structures for which the store_vjp calls are parallelized over num_proc, with no multi-processing inside store_vjp.
Ideally, some day we can refactor that, e.g. if PolySlab is fully vectorized, and GeometryGroup could be unraveled, maybe.

Parallelizing store_vjp over structures

---

tests/sims/simulation_2_3_0rc2.json
tests/test_web/test_webapi.py
tidy3d/web/webapi.py

The `estimate_cost` test was hanging because it now relies on `get_info` having a `metadataStatus` field, and waits for it. The `detail` request that is called by the `get_info` function, and the function itself, were overwritten/monkeypatched in various ways all over the test file, which was causing some unwanted effects. I refactored things such that it is just defined once. Similarly for the `metadata` api call.

Fixing stuck estimate_cost test and reorganizing web api mock tests in general

---

tidy3d/components/source.py

Updating docstrings to specify that the coordinates are w.r.t. the source center. Also rewording the CustomFieldSource docstrign.
Note that I modified the notebook too. https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/228

Updating docstrings for custom field and custom current sources

---

CHANGELOG.md
tests/test_web/test_webapi.py
tidy3d/components/simulation.py
tidy3d/plugins/mode/web.py
tidy3d/web/container.py
tidy3d/web/webapi.py

Also included a flag in the pre upload validator to optionally raise an error if no sources are present in the simulation. This flag is true by default on `run` and manual job creation, but false for the mode solver. It cannot be changed from `run` (only in `Job` or `Batch`), because simulations with no sources should be very rare and we already have a lot of arguments in `run`.

Change missing source from warning to info (#813)

---

CHANGELOG.md
tidy3d/components/data/monitor_data.py
tidy3d/components/data/sim_data.py

To add up to the thoughts in #839: considering the grid points where the calculation is performed comes from `SimulationData`, creating a `poyting` method directly in `MonitorData` would end up more convoluted than just exposing a method to apply the correction from the 2D monitor. That's the reson for the current implementation.
Just to make sure: @momchil-flex, the correction should be applied in the case of a 2D monitor no matter the grid points, right? Or am I misunderstanding the correction factor?

Grid correction to Poynting  in 2D monitor (#839)

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/components/medium.py

context: a user was constructing a complex-valued permittivity array and passing it to JaxCustomMedium. Was getting some obscure jax error saying it couldn't multiply float and complex. Seemed to be coming from the backdrop step and in the user's setting up of the complex array. After digging around a while, I realized it was because the data in the vjp of JaxCustomMedium has taken the real part. This is not only ignoring the gradient w.r.t. the complex part but also making the values dtype of float, which I guess was causing this issue. This PR fixes both things.

fix adjoint plugin with complex-valued permittivity inputs

---

CHANGELOG.md
tidy3d/components/simulation.py
tidy3d/components/viz.py

fix: plot 3d format
thank you for your help

feat(SCEM-3114): plot3d little polish

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/utils/filter.py
tidy3d/plugins/adjoint/utils/penalty.py

Corresponding notebook: https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/237
Note: The optimizer is super basic, I'm not sure I will even document it for now, just testing it internally. Eventually we will probably want to either find a good Jax-compatible optimizer  (preferred) or put a lot of effort into making our own.
results from adding filter and binarized to notebook 3

filtering, projection, penalization, and optimization convenience wrappers for adjoint plugin

---

CHANGELOG.md
tests/test_plugins/test_dispersion_fitter.py
tidy3d/plugins/dispersion/__init__.py
tidy3d/plugins/dispersion/fit_fast.py

- Passivity enforcement and lossless materials via lower and upper bounds on loss
- Weighting real / imaginary part
- Fitting of eps_inf
- Running with eps_inf=None can give worse results than running with fixed eps_inf
- Works quite well on every material in library except the following two:
- Pd-JohnsonChristy1972, Ni-JohnsonChristy1972

Added fast dispersion fitter

---

CHANGELOG.md
tests/sims/simulation_2_3_0.json
tests/sims/simulation_2_4_0rc1.json
tests/test_components/test_IO.py
tests/test_components/test_source.py
tests/utils.py
tidy3d/__init__.py
tidy3d/components/data/dataset.py
tidy3d/components/simulation.py
tidy3d/components/source.py

Features:
- Validation heuristic for sufficiently fast sampling to avoid interpolation artifacts

Added CustomSourceTime

---

CHANGELOG.md
tidy3d/plugins/smatrix/smatrix.py

In case this is found to be the source of discrepancy in tests.
Not sure if it warrants a patch or we should merge into pre/2.4

remove redundant phase from shifted source in smatrix

---

CHANGELOG.md
test_local.sh
tests/test_components/test_medium.py
tests/test_components/test_parameter_perturbation.py
tests/test_components/test_simulation.py
tests/test_data/test_data_arrays.py
tests/test_plugins/test_dispersion_fitter.py
tidy3d/__init__.py
tidy3d/components/data/data_array.py
tidy3d/components/medium.py
tidy3d/components/parameter_perturbation.py
tidy3d/components/simulation.py
tidy3d/components/validators.py
tidy3d/constants.py
tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/dispersion/web.py
tox.ini

Heat and charge perturbation functionality. Currently, implemented for `Medium` and `PoleResidue`, but this is ready for an initial "big picture" review, to check if anything seems bad/needs a rework. Here's a notebook with demonstrations and explanations to help the review https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/daniil/perturbation-medium/docs/source/notebooks/PerturbationMedium.ipynb. If everything looks more or less alright, I will go ahead and finish some remaining to-do's:
tagging @momchil-flex just in case

Medium perturbation

---

tests/test_components/test_geometry.py
tidy3d/components/simulation.py

The `custom_datasets` had the wrong logic. It was looping through geometry group items but not checking if they were TriangleMesh before grabbing the datasets. Was breaking Anderson localization (and probably metalens) notebooks.
For now, omitting changelog item since this bug was introduced in [this commit ](https://github.com/flexcompute/tidy3d/commit/264a745ccfc10b5ae7ed90b62b43a018b096fdc1) and doesn't affect develop.

fix trianglemesh custom_dataset bug

---

tests/sims/simulation_2_4_0rc2.json
tests/test_components/test_source.py
tidy3d/components/simulation.py
tidy3d/components/source.py

Changed `CustomSourceTime` to accept a (real or complex) envelope, and automatically multiply it by `e^{i \omega_0 t}`. This particular complex modulation is needed for it to accept the phase shift from the different source types (e.g. `e^{i k_0 \cdot r}` for `PlaneWave`). Currently, one could put in `cos(\omega_0 t)` time dependence (or even something stranger), which leads to inaccuracies when attempting the phase shift. Having automatic complex modulation removes these inaccuracies.

Changed CustomSourceTime to automatically modulate at freq0

---

CHANGELOG.md
tests/sims/simulation_2_4_0rc2.json
tests/test_components/test_source.py
tidy3d/components/source.py

Per this issue:
https://github.com/flexcompute/tidy3d/issues/690

Option to allow DC component in GaussianPulse spectrum

---

CHANGELOG.md
requirements/jax.txt
tox.ini

previously we needed to install jax 3.* on windows and add a specific pip find link, apparently now jax is supported normally on windows so we dont have to handle this special case.

install jax normally on windows

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tests/utils.py
tidy3d/plugins/adjoint/components/simulation.py

Fixes #1062.
This PR basically includes all of the structures when `JaxSimulation.plot_structures` or `JaxSimulation.plot_eps_structures` is called. The latter is used in `SimulationData.plot_field()`. Previously, this was being ignored in some `plot_field()` plots but after this change, it works

include `input_structures` in jax_sim_data.plot_field()

---

CHANGELOG.md
tidy3d/plugins/adjoint/utils/penalty.py

previously, I smoothed the radius of curvature calculation by adding 1e-2 to the denominator. This avoided it going to infinity for infinitely straight edges. However, when the actual radius of curvature was close to 1e-2 it gave inaccurate results. Instead, I made the penalty function a numerically stable version for x > 0, which solves the issue more generally.
penalty(x) = 1/(1 + exp(x))
penalty(x)= exp(-x)/(1 + exp(-x))

numerically stable radius penalty

---

CHANGELOG.md
tests/sims/simulation_2_4_0rc2.json
tests/test_components/test_medium.py
tests/utils.py
tidy3d/__init__.py
tidy3d/components/medium.py
tidy3d/components/simulation.py

Known limitations:
- Currently only supports non-dispersive Medium

Added NonlinearSusceptibility with chi3 support

---

CHANGELOG.md
tests/test_components/test_field_projection.py
tests/test_components/test_grid.py
tests/test_components/test_monitor.py
tests/test_components/test_simulation.py
tests/test_data/test_data_arrays.py
tests/test_data/test_monitor_data.py
tests/test_data/test_sim_data.py
tests/test_plugins/test_adjoint.py
tests/test_plugins/test_mode_solver.py
tests/utils.py
tidy3d/components/data/dataset.py
tidy3d/components/data/monitor_data.py
tidy3d/components/data/sim_data.py
tidy3d/components/field_projection.py
tidy3d/components/grid/grid.py
tidy3d/components/monitor.py
tidy3d/components/simulation.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/simulation.py
tidy3d/plugins/mode/mode_solver.py

[backend PR](https://github.com/flexcompute/tidy3d-core/pull/323)
From a user point of view, the most notable changes of this PR are as described in the title:
- FieldTimeMonitor-s and FieldMonitor-s that have `colocate=True` return fields colocated to the grid *boundaries* rather than centers.
- `colocate` = True is now set by default.
- The `colocate` argument was also introduced in the `ModeSolver` and `ModeSolverMonitor`, also set to True by default.
The goal of this is to avoid some common confusions that users have about the field data, and also to make it easier to use the data outside of our python frontend.
Internally, various quantities like `flux`, `dot` and `poynting` also use colocation to boundaries, which however should not produce any noticeable difference as confirmed by …

Updating monitors to colocate to primal grid, and colocate=True by default

---

CHANGELOG.md
tidy3d/components/field_projection.py
tidy3d/log.py
tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/dispersion/fit_fast.py
tidy3d/plugins/mode/web.py
tidy3d/web/container.py
tidy3d/web/s3utils.py
tidy3d/web/simulation_task.py
tidy3d/web/webapi.py

Here's how we can adjust width of rich output, so that it should eliminate horizontal scroll bars in web documentation. Perhaps an alternative that we can consider is to define this width in the config, so that it could be changed as needed? What do you think? @tylerflex @momchil-flex

Rich console width

---

tests/test_components/test_geometry.py
tidy3d/components/geometry/base.py
tidy3d/components/geometry/polyslab.py
tidy3d/components/geometry/utils.py

Use the same grid size for both when loading vertices from GDSII, and apply dilations in the same manner to avoid unexpected differences due to operation order.

Equalize vertex processing in Geometry and PolySlab

---

tidy3d/components/simulation.py
tidy3d/components/source.py

This warning was previously necessary because undersampling CustomSourceTime could result in unanticipated sharp jumps in amp_time, which could lead to simulation artifacts. Now, CustomSourceTime is by default modulated at freq0. This means the typical use case can use a sampling time step much larger than the simulation dt without causing any problems.

Remove warning from CustomSourceTime

---

CHANGELOG.md
tidy3d/components/simulation.py

There were some things that got messed up with the simulation plotting that this fixes. It also fixes the deeper issue with #1061, which was that a 1D line was being created instead of a plane. In this commit, if the `plane` has any transverse dimensions of size 0, they are reset to `inf` so we always should have a 2D plane.

fix 2d intersection plotting in Simulation

---

tests/test_components/test_geometry.py
tidy3d/components/geometry/base.py

Reinstate `Geometry.intersections_2dbox` to avoid breaking backwards compatibility.

Fix backwards compatibility break

---

CHANGELOG.md
tests/test_package/test_parametric_variants.py
tidy3d/material_library/parametric_materials.py

Previously, a lower limit used for fitting the interband term was also used in frequency_range. It's better to set the lower limit of frequency_range to zero, since the Drude behavior is valid to DC

Extended lower limit of frequency range for graphene

---

tidy3d/web/webapi.py

Previously, the final update of the progressbar could leave it at a field decay status which is not the final one and it was looking weird (e.g. saying field_decay ~1e-2 in one case while the final one was 1e-6).

Final status update in web.monitor with the correct field decay

---

CHANGELOG.md
tests/test_components/test_medium.py
tests/test_components/test_simulation.py
tidy3d/components/medium.py
tidy3d/components/simulation.py
tidy3d/components/structure.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/structure.py

This adds a warning when a 2D geometry doesn't have a 2D medium.
@tylerflex it seems to break the adjoint tests, which has 0-thickness structures in a 2D sim. Is it possible to change these thicknesses to some other value, like td.inf? This may be more robust anyway without changing the intended behavior.
@tomflexcompute , this should also fix the plot_eps warning

Improved warnings with Medium2D

---

tidy3d/web/cli/constants.py

Tries to read the `TIDY3D_DIR` environment variable to set tidy3d's base directory and defaults to the current behavior. Partially solves #1131 and is what I am currently using.

Make TIDY3D_DIR configurable via environment variable

---

tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/utils/filter.py

* Adds a `CircularFilter`, which is just a uniform "cylinder" kernel instead of a conic kernel.
* Rename `feature_size` to `radius` in the circular filters.
* Remove extra factor of `sqrt(3)` in the radius calculation, which is inconsistent with literature.
Note: initial testing of the circular filter is showing that it's terrible compared to conic filter, so not mentioning it in the changelog for now.

adjoint filter cleanup and additions

---

tests/test_components/test_medium.py
tests/test_components/test_simulation.py
tidy3d/components/simulation.py
tidy3d/components/structure.py

Now, it does not warn if a structure has a 2d geometry without a Medium2D (e.g. for override_structures). It will only warn if the structure is added to Simulation.structures.
This is to fix this issue:
https://github.com/flexcompute/tidy3d/issues/1135

Moved warning for 2d geometry without Medium2D to Simulation.structures

---

tests/_test_local/_test_adjoint_performance_multi.py

Adds a local test of adjoint processing speed on a metalens problem.
Figured it would be nice to get it into the codebase in case we needed it in the future.

add a local adjoint speed test

---

tests/test_package/test_log.py
tidy3d/components/base.py
tidy3d/components/data/monitor_data.py
tidy3d/components/grid/grid_spec.py
tidy3d/components/medium.py
tidy3d/components/parameter_perturbation.py
tidy3d/components/simulation.py
tidy3d/components/source.py
tidy3d/components/validators.py
tidy3d/log.py
tidy3d/plugins/adjoint/components/structure.py

While trying to incorporate warnings capture into GUI, MC team noticed that when we have validation errors, setting `td.log.set_capture(True)` changes returned validation errors to something not very informative. This happens because during initialization of models we use `try-finally` in `Tidy3dBaseModel.__init__()` https://github.com/flexcompute/tidy3d/pull/1136/files#diff-d331aef8c3290adc3733d4ce375c5a4b139ad41bd5634113ca404cc827e3d949L76-R82 to try to finish warning capture no matter what. But our warning capture parsing assumes the models are well-built. So, when there are validation errors the instances are incomplete and parsing produces its own errors that are not related to simulation validation. 
A seemingly straightforward way to fix this is to just remove `try-finally` …

Fix warning capture

---

tests/test_data/test_sim_data.py
tidy3d/components/data/monitor_data.py
tidy3d/components/data/sim_data.py

Avoid using `grid_corrected_copy` when computing things like flux and poynting internally in order to skip some data copying which can be slow for large data.

Reorganizing grid correction application

---

CHANGELOG.md
tests/test_components/test_mode.py
tidy3d/components/mode.py

@momchil-flex I'm not sure this goes into 2.4, given the timing, so I added the changes in the "unreleased" section of the changelog.

Fixes for group_index_step validator (#1143)

---

tests/test_components/test_geometry.py
tidy3d/components/geometry/polyslab.py

Resolves #1147, and additionally other inf related handling in PolySlab. This issue only arises in a polyslab of vertical sidewall, as a slanted polyslab of infinite thickness will for sure self intersect.

Fixing inf bounds handling in PolySlab

---

CHANGELOG.md
tests/sims/simulation_2_4_1.json
tests/test_plugins/test_mode_solver.py
tidy3d/components/data/monitor_data.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/mode/solver.py

We've had a `filter_pol` option in the mode spec for a while, but until now this was always computing the polarization fraction under the hood. Furthermore, this was not even taking the nonuniform grid into account, nor the fact that for angled modes, the field components need to be rotated to the frame in which the propagation axis is z in order to compute polarization fraction properly (i.e. TE/TM is defined w.r.t. the plane normal to the propagation direction, which is not the same as the mode plane normal in the case of angled modes).
I also added a `ModeSolverData.to_dataframe()` method that conveniently gathers all sorts of mode information:
There is one remaining problem. I added a test that compares all properties between nominally identical waveguides, one with an angle and one …

Polarization fraction of modes; and collected information as a dataframe

---

CHANGELOG.md
tests/test_components/test_medium.py
tidy3d/components/medium.py
tidy3d/plugins/dispersion/fit_fast.py

- Computes max Im[eps] of a pole residue model in its frequency_range. If frequency_range is None, over all frequencies. The extrema finder function is moved from fit_fast. @caseyflex could you please verify if anything in this PR breaks fitter?
Note that the old extrema finder has an issue: previously my focus was only to find if Im[eps] can be negative, so I wasn't paying attention if it's the extrema of Im[eps] or any quantity proportional to Im[eps]. As I checked today, the old extrema is for Im[eps]/freq, so it'll be off if you care more than just the sign of Im[eps]. It should be fixed now in this PR. 
- Fix Sellemier model `eps_model` error when wavelength ** 2 < C_i
- @e-g-melo For Palik lossless medium, please checkout the added tests. The first two materials have large loss: …

Compute loss upper bound in PoleResidue

---

CHANGELOG.md
tidy3d/log.py

request from zongfu to remove the line number output in the webapi functions, eg the stuff on the right
Seems this info is irrelevant and clutters the output a bit

remove line number in webapi output

---

CHANGELOG.md
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/medium.py

It was previously trying to measure the permittivity inside by looking two grid cells inside of the boundary. This was causing errors when the PermittivityData for the box was less than 1 grid cell thick. This PR fixes this.

fix adjoint for very thin box

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/components/base.py

This should work with your particle swarm notebook now. I just tried it. 
Basically what this does is converts the `polyslab.vertices` to a list in the intermediate representation that jax handles. this was because jax was not able to handle an untracked multi-dimensional array

fix bug with PolySlab in JaxSimulation.structures

---

CHANGELOG.md
tidy3d/components/geometry/base.py

Minor simplification in return from `Geometry.from_gds` to avoid creating a group with a single element.

Avoid creating unecessary geometry groups of single elements

---

CHANGELOG.md
tests/test_components/test_monitor.py
tests/test_components/test_simulation.py
tests/test_package/test_log.py
tidy3d/components/monitor.py
tidy3d/components/simulation.py
tidy3d/components/source.py

I went with just warnings for now, including warnings that the behavior may change to a hard constraint in the future, if we decide to impose some strict limits e.g. in 2.5.

Warn if too many frequencies; too many modes; or too many grid points in mode source or monitor

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tests/utils.py
tidy3d/components/data/monitor_data.py
tidy3d/plugins/adjoint/components/base.py
tidy3d/plugins/adjoint/components/data/data_array.py
tidy3d/plugins/adjoint/components/data/sim_data.py

1. When `FieldMonitor` objects were in `JaxSimulation.output_monitors` and `.flux` was called with symmetry, the symmetry covered areas were being included in the flux calculation and therefore giving `nan` as the interpolation coordinates were outside of the data range. Temporarily fixed this to avoid errors by converting `nan` values to `0`, but not sure if this is the appropriate way to handle it. For example, may undercount flux by 2x, 4x, 8x, depending on how many symmetry planes there are. Seems the deeper problem is that the fields are not getting copied over to the symmetry regions. spent a while trying to figure it out but got quite confused by the FieldData internals.
2. Same obscure `PytreeDef` error was occurring when a regular `JaxSimulation.monitor` had a `.freqs` field as a …

A few more adjoint fixes

---

CHANGELOG.md
tidy3d/plugins/adjoint/components/base.py

adjoint has the same error as before if an `output_monitor` has `freqs` as a np.ndarray.
we can either fix this in 2.4.3 or try to get it into the 2.5 pre-release

fix bug with freqs as np.ndarray in output monitors

---

tests/data/monitors.lsf
tests/test_package/test_convert.py
tidy3d/web/cli/converter.py

Added capability to parse in the following (marked in green) monitors from lsf. These are permittivity monitors, field time monitors, and field monitors expressed in different solvers. I currently have it so that monitors that record the same information but in different solver regimes (e.g. addindex vs addemeindex) route to the same function in the parser.
This should thus handle every monitor instance in lumerical for which there is a Tidy3D counterpart.
Also added monitor.lsf as an example lsf file for testing that includes an example of every monitor we can handle, and a patch-up handling cases where no e.g. sources, structures, monitors, and override structures are given.

lsf - added more monitor parsing capability

---

CHANGELOG.md
tests/test_components/test_monitor.py
tidy3d/components/monitor.py

Requested by https://flow360.atlassian.net/browse/SCEM-2172

better description for TimeMonitor.interval

---

CHANGELOG.md
tidy3d/components/geometry/base.py
tidy3d/components/simulation.py

I was playing with a large metalens file and wanted to profile the initialization time (~2.5 minutes). One thing I noticed is that the new `_validate_2d_geometry_has_2d_medium` validator was taking a noticeable chunk of the time (~50s), essentially because it was working with `geometry.bounding_box` instead of `geometry.bounds`. The former constructs a `Box` object which adds a lot of overhead when dealing with hundreds of thousands of geometries.
This PR does a few things:
- Adds a test for generating a metalens simulation with 10k structures, and the test will fail if this doesn't work within 3s. Currently, it succeeds in about 2.1s, so if something heavy gets added inadvertently, this should alert us.
- Introduces a `Profile` context in `tests/utils.py` and uses that in the test to …

Test initialization speed of a metalens with 10_000 structures

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/components/source.py
tidy3d/plugins/adjoint/components/data/monitor_data.py
tidy3d/plugins/adjoint/components/data/sim_data.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/medium.py
tidy3d/plugins/adjoint/components/simulation.py
tidy3d/plugins/adjoint/components/structure.py
tidy3d/plugins/adjoint/web.py

same as #1179 but rebased against 2.5, squashed, and polished up.
Note: works fine on version 2.4.2 but fails with version 2.5.0rc1 for some reason, looking into this.
Also note: there are two added tests (`_test_adjoint_broadband ...`) that should go in core.
Summary of changes:
* users can now add multiple frequencies to `output_monitors` and also different `output_monitors` can have different frequencies.
* internally, we maintain a sorted list of `freqs_adjoint` corresponding to these monitors, which become the `freq0`s of our adjoint sources.
* if not set by `JaxSimulation.fwidth_adjoint`, the `fwidth` of the adjoint sources is chosen to be smaller than some factor (0.1) times the minimum difference between the `freqs_adjoint`. This was chosen empirically to be small enough to have …

broadband adjoint (2.5)

---

CHANGELOG.md
tests/test_components/test_geometry.py
tests/test_components/test_simulation.py
tests/test_components/test_structure.py
tidy3d/components/geometry/base.py
tidy3d/components/geometry/utils.py
tidy3d/components/simulation.py
tidy3d/components/structure.py

Structures with custom medium are intersected with their medium contours at a given permittivity threshold.

Add `to_gds` to `Simulation`, `Structure` and `Geometry` (#883)

---

CHANGELOG.md
requirements/web.txt

This unpins the versions of boto and click, see #1209 
I tested with our webapi notebook with
```
click==8.0.3
boto3==1.23.1
```
and it worked fine 
@magiWei do you see any issues with this?

unpin boto and click

---

.github/workflows/run_tests.yml
CHANGELOG.md
setup.py
tests/test_components/test_monitor.py
tidy3d/components/monitor.py
tox.ini

Just a few things we were going to change for 2.5, before I forget. Might be more, so we can keep this open and add to it as needed or merge whenever.
- Python 3.7 no longer guaranteed to be supported.
- Remove colocation deprecation warning.

2.5 changes

---

CHANGELOG.md
tests/test_components/test_time_modulation.py
tidy3d/__init__.py
tidy3d/components/medium.py
tidy3d/components/simulation.py
tidy3d/components/source.py
tidy3d/components/time.py
tidy3d/components/time_modulation.py

TODO:
This PR adds two fields ~~`permittivity_modulation` and `conductivity_modulation`~~ `modulation_spec` to `Medium`. 
With modulation, the permittivity (conductivity) of a medium is a linear summation of time-independent and dynamic parts. As for the dynamic part, it can be a function of both space and time: `modulation_amp(r, t)`. Similar to source, i think we can just support the case where space and time are separable: `modulation_amp(r, t) = Re[amp_time(t) amp_space(r)]`. This should cover most applications, and is more efficient to support in the backend.
- `modulation_amp(r, t)` is described by the class `SpaceTimeModulation` that has two fields: `space_modulation` and `time_modulation`. The default `space_modulation` is uniform in space 
- `SpaceModulation` class defines …

Space-time modulation of all types of materials

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/components/data/sim_data.py

This is a quick and dirty way of fixing things, but it should work. If no adjoint sources detected:
* make a point dipole at the center of the simulation with amplitude=0
* set the run time to something around 1/fwidth to avoid unnecessary long runtime.
This assumes that the simulation will still run if the only source has an amplitude of 0. @momchil-flex do you know? If there was some auto-detection of this case (or when no sources are present) that returned zero'd out data that could be another way to handle things.
Main downside of this is that it charges a useless simulation to the user, but I think to do this properly would require a lot of construction, so I wanted to throw this out there to discuss as a medium-short term fix to this relatively uncommon edge case.
I also am not sure …

handle case with no adjoint sources

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/utils/filter.py

If the filter radius was larger than the input array (in pixels) along any dimension, scipy raised an error.
Now, we log a warning and truncate the kernel along that dimension to match the input shape (note that the kernel is odd, so it might be 1 smaller if the input shape is even)
I also added a switch if we want to instead raise, maybe this is unnecessary.

Truncate circular filter in edge case

---

tests/test_components/test_medium.py
tidy3d/components/medium.py

Previously, the following
```
import tidy3d as td
td.Medium(permittivity=2).eps_model(np.array([1,2]))
```
gave an error:
```
OverflowError: Python int too large to convert to C long
```

Fix bug in eps_model for integer frequency arrays

---

CHANGELOG.md
tests/test_components/test_structure.py
tidy3d/components/structure.py

The 0D case is also handled just to avoid an obscure error.

Correctly handle 2D/1D custom medium when exporting to GDS

---

CHANGELOG.md
tests/test_components/test_IO.py
tidy3d/components/data/sim_data.py

Syntax:
```py
mnt_data = SimulationData.mnt_data_from_file(fname, mnt_name, **kwargs)
```
loads a monitor data from a subgroup in the `SimulationData` file.
1. grabs the `JSON_STRING` to get the monitor type info.
2. Looks up the proper `MonitorDataType`
3. Iterates through the hdf5 file until a match is found on monitor name
4. Uses `MonitorData.from_file()` with a constructed group path to do the loading.
Some error checking thrown in, only works with `.hdf5` files at the moment.

adds `SimulationData.mnt_data_from_file()` method to load individual `MonitorData`

---

CHANGELOG.md
tests/test_plugins/test_component_modeler.py
tidy3d/components/base.py
tidy3d/plugins/smatrix/smatrix.py

Uses deterministic hash for the batch path that doesn't change between sessions

Fix Component Modeler Batch Path

---

CHANGELOG.md
tests/test_data/test_monitor_data.py
tests/test_data/test_sim_data.py
tidy3d/components/data/dataset.py
tidy3d/components/data/sim_data.py

#1261 
Adds
*  `FieldData.apply_phase(phase :float) -> FieldData`
* `phase` argument to `SimulationData.plot_field` that either
* applies a phase to the field data being plotted (if complex-valued)
* warns the user that it will be ignored (if real-valued and phase is non-zero)

apply phase to `FieldData` and `SimulationData.plot_field`

---

CHANGELOG.md
tests/test_plugins/test_mode_solver.py
tidy3d/components/data/monitor_data.py
tidy3d/components/monitor.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/mode/solver.py

This was motivated by two things when using the default single precision:
- Smaller file size for download
- Smaller chance of OOM which can sometimes happen for very large mode solves in the post-processing (colocating, normalizing, sorting modes).

Ensuring mode solver fields are returned in requested precision

---

CHANGELOG.md
tests/test_components/test_simulation.py
tests/test_plugins/test_mode_solver.py
tidy3d/components/monitor.py
tidy3d/components/simulation.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/web/api/mode.py

Currently, monitors that produce a small amount of data but may need a large amount of memory internally are not really validated to prevent OOM on our servers. I was thinking on imposing some limits like max number of freqs, or product of num_freqs x num_points x num_modes for mode monitors, etc. but I realized what probably makes the most sense is restricting the data size of the associated *field* monitor, which is always needed internally.

Enforcing limits on the internal memory needed by monitors

---

tests/test_data/_test_datasets_no_vtk.py
tests/test_data/test_datasets.py
tidy3d/components/data/dataset.py
tidy3d/components/types.py

For some reason couldn't make it work with plain global variables, so ended up using a dict that contains relevant info. One issue with it (and probably in general using this on the fly approach) is that we can't use imported modules members in definition of function signatures. For this particular case, it is not critical, but could be for others.

On the fly vtk import

---

CHANGELOG.md
tidy3d/components/field_projection.py
tidy3d/components/monitor.py

Backend PR: https://github.com/flexcompute/tidy3d-core/pull/474
Addresses [this](https://github.com/flexcompute/tidy3d/issues/1287) issue.

Allow field projections through a manually-specified medium

---

tidy3d/web/api/webapi.py
tidy3d/web/core/task_info.py

Note: post-processing charge is currently only incurred by field projection monitors.

Print cost breakdown in estimate_cost if there is mode or post-procesing charge

---

tidy3d/plugins/mode/mode_solver.py

Whether `eps_model` works with an array of frequencies is not consistent among the various media. Earlier I had an issue with fully anisotropic which I fixed, but now I see that the same is true for (some?) custom media. Since fully clarifying that may be a mess, and for this particular check looking at the central freqeuncy is probably fine, I propose this change for now.
Of course I could also iterate over `freqs`, but I want this check to be very fast even in cases with e.g. large custom media / many freqs, so I chose not to.

Mode solver eps_complex check at central frequency only

---

tidy3d/plugins/dispersion/fit_fast.py

I also fixed an error that was arising when both logspacing and smooth advanced parameters were set.

Added max_num_poles at least min_num_poles validator to FastDispersionFitter

---

CHANGELOG.md
requirements/jax.txt
tests/test_package/test_log.py
tests/utils.py

@daquinteroflex note: when we merge this, we should also update it in the docs refractor.

bump `jax` and `jaxlib` versions to `0.4.*`

---

CHANGELOG.md
tests/test_components/test_meshgenerate.py
tests/test_components/test_simulation.py
tidy3d/components/grid/mesher.py

Warn when structures are too small compared to the generated mesh.
Also realized that e.g. placing a thin `MeshOverrideStructure` of size dl and mesh step dl will *not* place boundaries on both sides of that structure (i.e. a single mesh step) because of the way the `isclose` check is done. Changed tolerances a bit to fix this as it should be expected behavior.
I also added more docstrings explaining how that part of the mesher works. I must admit it's still a bit of a mess, but I don't have time for a complete overhaul (and it's not clear what that might look like).

Fix to mesher error in very specific cases

---

CHANGELOG.md
tests/test_plugins/test_mode_solver.py
tests/test_web/test_tidy3d_task.py
tests/test_web/test_webapi.py
tests/test_web/test_webapi_heat.py
tidy3d/version.py
tidy3d/web/api/mode.py
tidy3d/web/core/constants.py
tidy3d/web/core/s3utils.py
tidy3d/web/core/task_core.py

So I've modified the solver to zip the result files, and I've verified that I can both run and load a simulation with this new solver, and that I can load old simulations from the server. However, I can't get all the tests that use mock functions to run. I don't exactly understand what's happening, but it has to do with my trying to make things a bit more general, and introducing `download_gz_file` in `s3utils.py`. Then it seems like instead of mocking `download_file` in `task_core` or `mode.web`, respectively, we should just be mocking it in `s3utils`. But I either get errors or even the tests hang when I try locally. @tylerflex could you help?

Using zipped solver data

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/components/simulation.py

Added validation for symmetry along zero size dimension

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/components/geometry/polyslab.py
tidy3d/plugins/adjoint/components/base.py
tidy3d/plugins/adjoint/components/data/data_array.py
tidy3d/plugins/adjoint/components/data/dataset.py
tidy3d/plugins/adjoint/components/data/monitor_data.py
tidy3d/plugins/adjoint/components/geometry.py
tidy3d/plugins/adjoint/components/medium.py
tidy3d/plugins/adjoint/components/structure.py
tidy3d/plugins/adjoint/components/types.py

This will be stage 1 of some future adjoint refactors. This one finally works though, and successfully separates the jax tracers from the original tidy3d fields. The main advantage of this is that we dont have to worry about the jax tracers interactively badly with the existing tidy3d validators and methods (eg. `Box.bounds()`).

adjoint refactor: stage 1

---

tests/test_components/test_simulation.py
tidy3d/components/apodization.py
tidy3d/components/base.py
tidy3d/components/base_sim/data/sim_data.py
tidy3d/components/base_sim/simulation.py
tidy3d/components/data/dataset.py
tidy3d/components/data/monitor_data.py
tidy3d/components/field_projection.py
tidy3d/components/geometry/polyslab.py
tidy3d/components/geometry/primitives.py
tidy3d/components/heat/data/monitor_data.py
tidy3d/components/heat/grid.py
tidy3d/components/heat/simulation.py
tidy3d/components/medium.py
tidy3d/components/mode.py
tidy3d/components/monitor.py
tidy3d/components/simulation.py
tidy3d/components/source.py
tidy3d/components/structure.py
tidy3d/components/time_modulation.py
tidy3d/components/validators.py
tidy3d/plugins/adjoint/components/data/data_array.py
tidy3d/plugins/adjoint/components/simulation.py
tidy3d/plugins/dispersion/fit.py
tidy3d/plugins/dispersion/fit_fast.py
tidy3d/plugins/dispersion/web.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/waveguide/rectangular_dielectric.py

After playing a little bit with it, managed to implement what we wanted as a convenient decorator. The usage as follows: instead of doing something like 
```
@pydantic.validator("monitors", always=True)
def _warn_monitor_simulation_frequency_range(cls, val, values):
"""Warn if any DFT monitors have frequencies outside of the simulation frequency range."""
if "sources" not in values:
raise ValidationError(
"could not validate `_warn_monitor_simulation_frequency_range` "
"as `sources` failed validation"
)
...
```
we can just do 
```
@pydantic.validator("monitors", always=True)
@check_previous_fields_validation(["sources"])
def _warn_monitor_simulation_frequency_range(cls, val, values):
"""Warn if any DFT monitors have frequencies outside of the simulation frequency range."""
...
```
this …

Unified validation check for dependency fields

---

CHANGELOG.md
tests/test_components/test_custom.py
tests/test_components/test_simulation.py
tests/test_components/test_time_modulation.py
tests/test_plugins/test_mode_solver.py
tidy3d/components/data/data_array.py
tidy3d/components/medium.py
tidy3d/components/monitor.py
tidy3d/components/scene.py
tidy3d/components/simulation.py
tidy3d/components/time_modulation.py
tidy3d/components/validators.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/web/api/mode.py

Implements https://github.com/flexcompute/tidy3d/issues/1191. That is, there is a new simulation method `.subsection(region: Box, ...)` that can be used to create a smaller simulation based on original one. 
- Most of simulation fields are inherited, but could be optionally overridden
- Grid can be requested to be the same as in the parent simulation (`grid_spec="identical"`). In this case it's converted into a custom grid and the requested region is expanded to match parent grid lines. One small issue here is that if the parent grid already matches the requested region, than due to numerical precision one additional cell might be included. But that doesn't seem cause any real issues.
- Similarly, due to numerical precision issues, even when child grid is essentially the same as the …

Reduced sim mode solver

---

pyproject.toml

We need a set of basic requirements to be able to build minimal webservices used for validation. I brought this file back from the grave it was sent to in 2.6. I am not sure if this is the best place for it, and also I guess it would be good if we can test somehow that these reqs are sufficient. I guess we could have a separate github action that only installs those and tries to run some of the tests that should work?

Bringing back basic requirements file

---

.github/workflows/sync-to-readthedocs-repo.yaml
.gitmodules
tests/full_test_notebooks.py

Hi Momchil,
I've improved the release process. 
So now:
-  You make a branch in `tidy3d/` that starts with the letter "v" like this example branch
- When you commit to this branch, the `sync-to-readthedocs` action will automatically make a branch in `tidy3d-docs` with the same name
- It will push the contents into that branch. 
You can see this worked well:
* https://github.com/flexcompute/tidy3d/actions/runs/7448894014/job/20264267298
* https://github.com/flexcompute-readthedocs/tidy3d-docs/tree/v_test_release
Then you can easily just build the documentation for that branch in the readthedocs admin page.
(I am unsure what happens when it is overwritten)

FEAT: Automatic release from branch v*

---

.github/workflows/sync-to-readthedocs-repo.yaml

After many closed branches attempts including with git subtree

 FIX: Sort out the sync submodule issue :thinking: 

---

tests/test_plugins/test_adjoint.py
tests/utils.py

fix for `lucas/fields_in_mode_data`

---

.github/workflows/release.yml

We used to have to manually generate release notes on GitHub through clicking
This workflow change makes this happen automatically:
from my testing on a dummy repo, I needed       
```
permissions:
contents: write
```
to get the release action to run at all, but maybe this is not related to the release notes and should be removed.

release workflow auto generates release notes

---

tidy3d/components/simulation.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/web/api/container.py
tidy3d/web/api/mode.py

- shrink bounds when performing `grid.discretize_inds` on new region to avoid including possible spurious pixel
- switch simulation reduction in mode solver to be automatic only for simulations with custom medium + display warning if that happens

Use simulation reduction automatically only in case of custom mediums

---

tidy3d/components/base_sim/simulation.py

This is just for convenience so we can call it regardless of the simulation type.

Adding validate_pre_upload to AbstractSimulation

---

CHANGELOG.md
scripts/test_local.sh
tests/test_data/_test_datasets_no_vtk.py
tests/test_data/test_datasets.py
tidy3d/components/data/dataset.py
tidy3d/components/parameter_perturbation.py

A small PR that came out of working on the charge example https://github.com/flexcompute/tidy3d-notebooks/pull/25 and it does two things:
- allows importing data fields from `.vtu` files with specific names if such files contain multiple fields (e.g. "Electrons", "Holes", etc)
- removes spurious warnings when reloading simulations containing `PerturbationMedium` with `CustomChargePerturbation`/`CustomHeatPerturbation`

Allow importing specific field from vtk

---

CHANGELOG.md
tests/sims/simulation_2_6_0rc1.json
tests/test_components/test_simulation.py
tests/test_data/test_data_arrays.py
tests/test_data/test_monitor_data.py
tests/test_data/test_sim_data.py
tests/test_plugins/test_adjoint.py
tests/utils.py
tidy3d/components/data/dataset.py
tidy3d/components/data/monitor_data.py
tidy3d/components/monitor.py

The implementation proposed here merges `ModeSolverData` and into `ModeData`. It also deprecates the use of `ModeSolverMonitor` and changes the implementation on `ModeSolverData` to be derived from `ModeData` (to avoid most code duplication and make deprecation later easier). There are 2 issues at this point:
1. `ModeSolverData` ended up inheriting the `amps` field, which will be unused.
2. This warning: https://github.com/flexcompute/tidy3d/blob/fa402883fafa3de37fbe0b22cbfb3b04e2263552/tidy3d/components/data/monitor_data.py#L105-L112 is being emitted (unnecessarily?) and getting caught in [an adjoint test](https://github.com/flexcompute/tidy3d/blob/fa402883fafa3de37fbe0b22cbfb3b04e2263552/tests/test_plugins/test_adjoint.py#L1618).
Thoughts, @tylerflex and @momchil-flex?

Add field data to ModeMonitor (#1274)

---

tidy3d/plugins/adjoint/utils/filter.py
tidy3d/plugins/adjoint/utils/penalty.py

sorry for another PR / commit here.
I just compiled the docs locally and noticed a couple things in the docstrings to improve.
Now they look like below and should be ok.

fix adjoint utils docstrings

---

CHANGELOG.md
tests/test_components/test_grid_spec.py
tests/test_components/test_simulation.py
tidy3d/components/geometry/utils_2d.py
tidy3d/components/simulation.py

Followed the main ideas in @caseyflex's [original PR](https://github.com/flexcompute/tidy3d/pull/1263) and some modifications added by in [Shashwat's PR](https://github.com/flexcompute/tidy3d/pull/1345) but made finding the correct adjacent media more robust by tracking extra information during the subdivision process. 
Limitations 
- intersections of 2D materials with 2D PECs are not reliable
- snapping 2D materials to the grid means that the precise plane where intersections are computed and the final position of the 2D material are slightly different

Allow inhomogeneous substrate and superstrate for 2d materials with more complex intersections

---

CHANGELOG.md
tests/test_data/test_sim_data.py
tidy3d/components/data/sim_data.py

If `SimulationData.plot_field(..., val="int")`, it would through an obscure unbound local error. Now it throws a KeyError telling the user to change `val` to a supported value.

fix obscure error if val not supported in SimData.plot_field

---

tidy3d/components/scene.py
tidy3d/components/simulation.py

Fixes https://github.com/flexcompute/tidy3d/issues/1442

fix plotting bounds in plot_structures

---

tidy3d/components/simulation.py

The changes in [the original inhomogeneous substrate/superstrate PR](https://github.com/flexcompute/tidy3d/pull/1395) broke a backend test that involved a 1D simulation. I just make sure now that the background simulation geometry has a nonzero size.

fix for innhomegenous substrates/superstrates in 1D and 2D simulations

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/components/boundary.py
tidy3d/components/simulation.py

Fixes #1444 
Interestingly, we already had such a validator. We warn in various cases, e.g. if the bloch vector of the boundaries does not match the angle of the source. However we were missing the case of periodic boundaries, which are a separate class from Bloch.
It would perhaps make sense to change the warning to error. I am not sure if there's any use case in which we want the simulation to run with a mismatched source angle. But, in order to avoid anything unexpected, I think keeping it a warning is also fine.

Warn if periodic boundaries are used with an angled source

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/__init__.py
tidy3d/components/grid/grid_spec.py
tidy3d/components/simulation.py
tidy3d/plugins/mode/mode_solver.py
tidy3d/plugins/mode/solver.py

Mode solver: the formulation of mode solver will follow the treatment in Benkler's paper (10.1109/TAP.2006.875909), where the split curl is treated as scaled permittivity and E-field. In the end of the mode solver, the E-field is scaled back. 
We also enable `incidence_matrix` when PEC subpixel is applied.

Support conformal mesh for PEC structures

---

tests/test_data/test_monitor_data.py
tidy3d/components/data/monitor_data.py

This is an alternative version of the previous PR: https://github.com/flexcompute/tidy3d/pull/1463
It still improves the efficiency by reducing the use of expensive xarray functions (it may be even faster than the previous version). However, it is no longer vectorized over frequency and mode_index, which removes the memory overhead from the previous PR.

(Alternative) Improved efficiency of outer_dot

---

tidy3d/components/data/monitor_data.py

Uses the faster outer_dot to improve efficiency of overlap_sort. Sometimes, sorting modes can be a bottleneck in mode solving, and this should prevent that from occuring.
Based off of https://github.com/flexcompute/tidy3d/pull/1464

Improved efficiency of overlap_sort

---

CHANGELOG.md
tidy3d/components/data/monitor_data.py
tidy3d/config.py
tidy3d/log.py
tidy3d/plugins/adjoint/components/simulation.py

I am extremely sorry @momchil-flex ! I accidentally deleted your branch whilst working on top of it to fix the Github actions issue. I will not do something like that again, and have learnt my lesson.
The old relevant PR is https://github.com/flexcompute/tidy3d/pull/1457 and I have just reset back to your commit as you can see. I will sort out the github actions issue in another branch. I am extremely sorry as I thought it was just a minor script update, but was not.
Relevant comments from Lucas were:
> I understand the changes required because of the backend log, so this looks fine. But thinking about the frontend only, is there any reason to use "USER" level instead of "INFO"? Or "SUPPORT" instead of "DEBUG"? I wonder if we should add a general comment for the future instructing …

Updates to help unify backend logging (Reset back to original #1457)

---

.github/workflows/release.yml
.github/workflows/sync-to-readthedocs-repo.yaml
docs/index.rst

RELEASE: Upgrade release flow and tiny fix :zap:

---

CHANGELOG.md
docs/api/material_library.rst
docs/generate_doc.py
tests/test_package/test_material_library.py
tidy3d/material_library/material_library.py
tidy3d/material_library/material_reference.py

Resolves #1413 
The doc page for LiNiO3:
One question to @daquinteroflex: now I need to manually run `python generate_doc.py` to update material_library.rst, so that the doc page can include updated material library. Is that the expected behavior?

Add uniaxial medium lithium niobate to material library

---

CHANGELOG.md
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/components/simulation.py

Previously it was
```py
run_time_adj = 100 / fwidth_adj
```
Now it is
```py
run_time_adj = run_time_fwd + 10 / fwidth_adj
```
#1403

more accurate adjoint run_time

---

CHANGELOG.md
tests/test_plugins/test_design.py
tidy3d/plugins/design/design.py
tidy3d/plugins/design/method.py
tidy3d/plugins/design/result.py

Addresses #1428 , now the user can do
```py
sweep_results = design_space.run_batch(scs_pre, scs_post)
batch_data = sweep_results.batch_data
for task_name, data in batch_data.items():
...
```
The `Results.task_ids` were left in for backwards compatibility, even if it's only been a few hours.

add BatchData to design.Results, if available

---

CHANGELOG.md
tidy3d/components/medium.py

Small bug when trying to plot epsilon with coord_key not equals to `centers` and `freq=None`. Other media assume an infinite frequency but PEC results in TypeError at multiplication
`eps_sample = sim.epsilon(box=box, coord_key="Ex")`

fix pec freq arg

---

.gitignore
CHANGELOG.md
docs/api/abstract_models.rst
docs/api/index.rst
docs/api/lumped_elements.rst
tests/sims/simulation_sample.json
tests/test_components/test_medium.py
tests/test_components/test_simulation.py
tests/test_plugins/terminal_component_modeler_def.py
tests/test_plugins/test_component_modeler.py
tests/test_plugins/test_terminal_component_modeler.py
tidy3d/__init__.py
tidy3d/components/geometry/utils_2d.py
tidy3d/components/lumped_element.py
tidy3d/components/simulation.py
tidy3d/components/source.py
tidy3d/components/viz.py
tidy3d/constants.py
tidy3d/plugins/smatrix/__init__.py
tidy3d/plugins/smatrix/component_modelers/base.py
tidy3d/plugins/smatrix/component_modelers/modal.py
tidy3d/plugins/smatrix/component_modelers/terminal.py
tidy3d/plugins/smatrix/ports/lumped.py
tidy3d/plugins/smatrix/ports/modal.py
tidy3d/web/api/container.py
tidy3d/web/api/webapi.py

Implements the original frontend changes by Shashwat in this [PR](https://github.com/flexcompute/tidy3d/pull/1341)
A couple of additions:
- Checks and possibly forces the lumped port to snap to the grid, since the sheet resistance is also automatically snapped to the grid
- Computes the current at each port using a complete contour, which alleviates some of the need for port refinement
- Fixes for some unit tests
Known limitations:
Not directly related to this PR, but 2D material intersections are a known issue at the moment. The lumped ports are 2D materials, which means they must connect to fully 3D materials. 
Supersedes [PR 1341](https://github.com/flexcompute/tidy3d/pull/1341)

added lumped ports to smatrix plugin

---

CHANGELOG.md
tidy3d/plugins/adjoint/components/data/monitor_data.py

When jax is upgraded, the adjoint quickstart fails when constructing adjoint source because `complex()` doesn't work for multi-dimensional jax arrays (even if just one data point).
```py
>>> import jax.numpy as jnp
>>> a = jnp.array([[1]])
>>> complex(a) 
(1+0j)
>>> complex(a)
TypeError: Only scalar arrays can be converted to Python scalars; got arr.ndim=2
```

fix adjoint bug for point monitor data from jax update

---

CHANGELOG.md
tidy3d/web/api/webapi.py

Tom pointed out that if a task is queued for a bit, some users don't realize what is happening, and terminate the notebook execution (while the task still runs eventually and users get charged). This is an attempt to improve our messaging. Here's what it looks like when a task is in queue now:

Small reorganization of web.monitor logging

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/components/monitor.py

So initially I wanted to make a small modification: for field monitors, if a subset of the field components is requested, the `storage_size` is just proportional to the number of requested components. However, the solver stores all of E if at least one E component is requested, and same for H. So the internal storage size for field monitors can be larger.
Then I noticed that the test for this was not working as expected: it was successful because of a completely unrelated error. Fixing the test led me to also fixing `DiffractionMonitor` solver storage estimate.

Fixes to some monitors' solver storage estimate, and to corresponding tests

---

CHANGELOG.md
tests/test_components/test_grid_spec.py
tests/test_components/test_simulation.py
tidy3d/components/grid/grid_spec.py
tidy3d/components/simulation.py
tidy3d/plugins/mode/mode_solver.py

- Bug in `ModeSolver.reduced_simulation_copy` that was causing mode profiles to be all `NaN`.
- Bug in `Simulation.subsection()` that was causing zero-size dimensions not to be preserved.
- Behavior of `UniformGrid` is made consistent with `AutoGrid` in case of zero-size dimensions. That is, grid is created as `[center - dl / 2, center + dl / 2]` instead of `[center, center + dl]`

Bugfixes related to simulation.subsection

---

CHANGELOG.md
tidy3d/web/core/s3utils.py

In 2.6 solver output is gziped, and it turns out that if we have something like `to_file="data/simulation_data.hdf5"` in web.run and the `data` folder does not exist, this would error. This had already been taken care of in the regular file download, now also fixing it for the gziped one which uses a tempfile when calling `download_file`, so the parent directory is not created there.

Creating parent directory for 'to_file' when downloading a gz file

---

tidy3d/plugins/smatrix/component_modelers/terminal.py

The E field is discontinuous at the port boundaries where conductors are present. In this picture the ground plane is at z=0 and the strip is at z=1000. Interpolation is inaccurate there, and even though only the end points are affected, it has a noticeable effect on accuracy.
Now, all field points outside the port bounds are ignored and linear extrapolation is used to estimate the E field on the exact port bounds.

Improve voltage computation for lumped ports

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

I was helping out @marc-flex and realised that the `ruff` version was not fixed. This caused a bit of mayhem in the linting, and is relatively urgent. I believe progressively everyone migrating to this version until we decide to change it will occur file by file.

FEAT: Urgent update ruff version fix :running:

---

CHANGELOG.md
tests/test_components/test_geometry.py
tidy3d/components/geometry/polyslab.py

Resolves #1539
Two main changes:
- In computing `center_axis`, replace `inf` with `LARGE_NUMBER`;
- Use `.finite_length_axis` instead of `.length_axis` .

Fix PolySlab intersections when bounds contain inf

---

tidy3d/plugins/design/method.py
tidy3d/plugins/smatrix/smatrix.py
tidy3d/web/api/webapi.py

@momchil-flex @lei-flex 
I need to get statistics about how many tasks are run from `adjoint`, `design` and `smatrix` plugins.
One simple way is to pass the plugin name through `simulation_type`, similar to how we do it for `adjoint`.
I'm proposing a change here that passes `simulation_type` for batches run in `design` and `smatrix`. and then in the backend we can treat these as regular `"tidy3d"` simulation types?
Let me know if you have a better solution. 
One thing that could make this easier is to do eg. `"tidy3d_design"` `"tidy3d_smatrix"` and then in the backend, we do the normal pipeline `if "tidy3d" in simulation_type`
let me know what you think

add tracking of `simulation_type` for smatrix and design plugins

---

CHANGELOG.md
tests/test_components/test_heat.py
tidy3d/components/heat/simulation.py

it now accepts 2D simulations and only raises error when 1D.
This PR (along with its corresponding PR on tidy3d-core) addresses issue [#555](https://github.com/flexcompute/tidy3d-core/issues/550) of tidy3d-core repo

Modified zero-size validator

---

tests/test_plugins/terminal_component_modeler_def.py
tests/test_plugins/test_terminal_component_modeler.py
tidy3d/plugins/smatrix/component_modelers/terminal.py

While testing a new example I found some issues with the way LumpedPorts are handled.
- Small bug in port snapping that was missed when changing interface, now have improved test coverage.
- For grids that do not line up exactly with LumpedPort bounds, the computation for current might choose the wrong bounding point.
- For very coarse grids there might not be a single data point within the port bounds, so I added a method that checks this condition before the simulations are launched.
I did not modify the changelog, since these are all changes that could be considered within the original LumpedPorts PR.

Fix: port computations for coarse grids

---

tests/test_components/test_IO.py
tests/test_components/test_custom.py
tests/test_components/test_meshgenerate.py
tests/test_components/test_parameter_perturbation.py
tests/test_components/test_scene.py
tests/test_components/test_simulation.py
tests/test_components/test_time_modulation.py
tests/test_data/test_datasets.py
tests/test_plugins/test_mode_solver.py
tests/utils.py
tidy3d/components/data/data_array.py
tidy3d/components/data/dataset.py
tidy3d/components/grid/grid.py
tidy3d/components/medium.py
tidy3d/components/parameter_perturbation.py
tidy3d/components/scene.py
tidy3d/components/simulation.py
tidy3d/version.py

This PR allows to use unstructured grid datasets (`TriangularGridDataset` and `TetrahedralGridDataset`) in unstructured medium classes. All necessary associated functionality is extended and tested, which includes:
- unstructured grid dataset interpolation improvement:
-- new vectorized interpolation
-- option `extrapolate` by nearest neighbor values
-- nearest neighbor interpolation
- loading `DataArray`  without coordinates (for example, when `arr = td.PointDataArray(np.ones((3, 2)), dims=["x", "y"])`, that is `dims` provided but not `coords`)
- `sel_inside` and `does_cover` for unstructured grid datasets
- `Coords.spatial_interp` is extended to work both with `SpatialDataArray` and `UnstructuredGridDataset`
There are quite a lot of changes, so maybe what would make sense is:
- for …

Unstructured custom medium

---

docs/development/release/index.rst
docs/development/release/version.rst
poetry.lock
poetry.toml
pyproject.toml
tidy3d/version.py

Works per and I think sorts out the version problem as it's basically compatible as before. This will do the release tag automatically too if we want too.
```bash
± |dario/2.6.2/fix_versioning ✓| → poetry run bump2version --dry-run --new-version 2.6.0rc2 minor --verbose
Reading config file .bumpversion.cfg:
[bumpversion]
current_version = 2.6.1
tag = true
commit = true
[bumpversion:file:pyproject.toml]
search = {current_version}
replace = {new_version}
[bumpversion:file:tidy3d/version.py]
search = {current_version}
replace = {new_version}
Attempting to increment part 'minor'
Values are now: major=2, minor=7, patch=0
Dry run active, won't touch any files.
New version will be '2.6.0rc2'
Asserting files pyproject.toml, tidy3d/version.py contain the version string...
current_version=2.6.1 …
```

BUILD: Improve versioning management :arrow_up:

---

CHANGELOG.md
pyproject.toml
tests/test_plugins/test_adjoint.py
tidy3d/plugins/adjoint/components/geometry.py

note: `docs/notebooks` also updated to latest `develop`

relax `sidwall_angle` validator -> warning in adjoint

---

CHANGELOG.md
poetry.lock
pyproject.toml
tidy3d/components/geometry/base.py
tidy3d/components/geometry/mesh.py
tidy3d/components/geometry/polyslab.py
tidy3d/components/geometry/primitives.py

To restore compatibility with gdsfactory. Ran tests with `trimesh=4.0.0` and `trimesh=4.1.8`.
@daquinteroflex can you take a look at `poetry.lock`? Something isn't right, I ran `poetry update trimesh` but it also changed `python-versions` and `[package.extras]`.
@lucas-flexcompute can you take a look at the gds-related files to see if I missed anything?

Bump trimesh version to >=4,<4.2

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/components/simulation.py

Restrict number of time points for non-0D field time monitors

---

CHANGELOG.md
docs/api/plugins/index.rst
docs/api/plugins/microwave.rst
tests/test_plugins/test_microwave.py
tests/utils.py
tidy3d/components/validators.py
tidy3d/plugins/microwave/__init__.py
tidy3d/plugins/microwave/impedance_calculator.py
tidy3d/plugins/microwave/path_integrals.py
tidy3d/plugins/smatrix/component_modelers/terminal.py
tidy3d/plugins/smatrix/ports/lumped.py

Addresses  [Issue 517](https://github.com/flexcompute/tidy3d-core/issues/517). Most of computations are done, now it is just a question of the best way to expose this functionality to users. I wonder if @weiliangjin2021 or @tylerflex have any input on whether we should start a "microwave" plugin that includes functionality that might not be commonly used in photonics. I mention that because it would be very easy to add time domain Voltage and Current monitors now.
Some tasks remaining:

FEAT: Compute characteristic impedance from fields

---

tests/_test_notebooks/full_test_notebooks.py
tests/test_components/test_grid_spec.py
tests/test_components/test_simulation.py
tidy3d/components/medium.py
tidy3d/components/simulation.py

Different subclass for volumeric equivalence of Medium2D

Zero thickness for volumetric equivalence of 2D material

---

CHANGELOG.md
tests/test_components/test_base.py
tests/test_components/test_grid.py
tidy3d/components/base.py
tidy3d/components/grid/grid.py
tidy3d/components/viz.py

Addresses #1352 
How do you all feel about this?
1. Used the name `.attrs`, because it follows the same [convention](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.attrs.html) as `xarray`, `pandas`, maybe others.
2. `attrs` are dictionaries (mutable) so they can be set on the fly, `sim.attrs['foo'] = bar`.
3. we still can't set the attrs directly since tidy3d objects dont support item assignment, eg.`sim.attrs = {}` doesn't work.
4. in `xarray`, attrs remain when the objects are copied and updated. but are removed when the objects are modified. We only need to handle the copy part since we can't modify tidy3d objects. therefore if `sim.copy()`, then the new object's attrs are the same.
5. Important point, since `attrs` are mutable, we want to ensure our internal code doesn't …

Add metadata to Tidy3D components

---

CHANGELOG.md
tests/test_components/test_simulation.py
tidy3d/__init__.py
tidy3d/components/run_time_spec.py
tidy3d/components/simulation.py
tidy3d/components/source.py
tidy3d/plugins/adjoint/components/simulation.py

Took a first stab at this. It's a bit messy and there are some edge cases but seems to work. We should discuss before I do anything more to it.
Note: the evaluated run_time is now `Simulation._run_time` so there will be bugs unless we change this in eg. the backend. I think I got all the instances in the front end.

Simulation.run_time accepts RunTimeSpec
