setup.py, tidy3d/version.py
Release 0.2.3 which finally works from pip and in docker notebooks.
=> First release working when pip installed from PyPI

tidy3d/components/monitor.py
Now takes interval into account when computing size, avoiding some bugs in a notebook
=> fixes monitor size bug for time domain (ignoring interval)

.pylintrc, tidy3d/components/geometry.py, tidy3d/components/monitor.py, tidy3d/components/source.py, tidy3d/components/viz.py
Adds arrows to source object plots when the sources have directionality.
Also monitors
Also polarization (E)
=> field source objects plot arrows now

CHANGELOG.md, test_local.sh, tests/test_components.py, tests/test_plugins.py, tidy3d/components/data.py, tidy3d/components/monitor.py, tidy3d/plugins/__init__.py, tidy3d/plugins/near2far/near2far.py, tidy3d/web/config.py
Following the advice on the Notion page, I have not rebased with develop yet.
@momchil-flex, regarding that small change in `data.py` about source normalization, recall that I changed `1j` --> `1` - not sure if this change should be propagated into develop, or if you've already accounted for this elsewhere.
=> Near2far improvements

tidy3d/plugins/near2far/near2far.py
`Near2Far` now throws an error if RCS is requested for a lossy background medium. Also changed variable names from `n, k` to `index_n, index_k` to avoid confusion with wave number.
=> Near2Far fix for lossy backgrounds

tidy3d/components/simulation.py
Gives more helpful validator messages:
* Which index into the medium, structures, monitors.
* Displays frequencies in scientific notation.
=> better error messages

tidy3d/components/simulation.py, tidy3d/web/webapi.py
still needs to add line in changelog, can add that after merge?
=> made run time optional, but must be >0 to upload

tidy3d/web/config.py
=> Config UAT -> Prod

tidy3d/components/base.py, tidy3d/components/data.py, tidy3d/components/medium.py, tidy3d/components/simulation.py, tidy3d/components/viz.py, tidy3d/plugins/dispersion/fit.py, tidy3d/plugins/smatrix/smatrix.py, tidy3d/web/container.py
suggested by LGTM
https://lgtm.com/logs/1ee00e7820930a1994d615666027891981122239/lang:python
=> code quality fixes

tidy3d/components/geometry.py, tidy3d/components/simulation.py, tidy3d/constants.py
also changed the large number constant, which was causing issues as float32(1e20)
much faster plotting
=> uses bounding box and simpler intersection checks in filter_structure

tidy3d/plugins/dispersion/fit_web.py, tidy3d/web/auth.py, tidy3d/web/httputils.py, tidy3d/web/webapi.py
=> Reverting requires_auth as it is already handled in handle_response

tidy3d/__init__.py, tidy3d/components/__init__.py, tidy3d/components/data.py
data.py uses pd.Field()
removed unnecessary code, like `type` and docstrings.
=> Data Cleanup

tidy3d/components/data.py
=> Adds 'intensity' label to xarray in plot_field with 'int'

tests/test_IO.py, tests/test_components.py, tests/utils.py, tidy3d/__init__.py, tidy3d/components/README.md, tidy3d/components/__init__.py, tidy3d/components/simulation.py, tidy3d/components/source.py
New organization following this inheritance chart
main changes:
* `VolumeSource` -> `UniformCurrentSource`
* Added `PointDipole` as a `UniformCurrentSource` that must have `size=(0,0,0)` (this is default too, type of `size` is `Tuple[Literal[0], Literal[0], Literal[0]] = (0,0,0)`.
* all sources have a `_dir_vector` and `_pol_vector` property that returns how the respective arrows should point, or `None` for no arrows, simplifies arrow stuff a good deal.
* injection axis is either a `@property` (for `PlanarSource`) or a `Field()` (for `VolumeSource`).
* `angle_theta`, and `angle_phi` are either a `@property` (for `ModeSource`) or a `Field()` (for `AngledFieldSource`).
* Added `TFSF` and `CustomFieldSource` templates, but they aren't usable as a `SourceType` in `Simulation.sources` yet …
=> Source reorg

pytest.ini, requirements/dev.txt, tests/test_IO.py, tests/test_components.py, tests/test_data.py, tests/test_log.py, tests/test_main.py, tests/test_plugins.py, tests/test_webapi.py, tidy3d/__main__.py, tidy3d/components/data.py, tox.ini
Still a lot of stuff requiring authentication that we can't test, but this increases the test coverage a good amount from 60% to 76% and caught a few minor issues.
To run coverage report
```
pytest -rA --cov=tidy3d tests
```
you may need to `pip install pytest-cov`
```
---------- coverage: platform darwin, python 3.6.7-final-0 -----------
Name                                                           Stmts   Miss  Cover
----------------------------------------------------------------------------------
tidy3d/__init__.py                                                31      0   100%
tidy3d/__main__.py                                                53     18    66%
tidy3d/components/__init__.py                                     19      0   100%
tidy3d/components/base.py …
```
=> increase test coverage

tidy3d/components/data.py, tidy3d/plugins/mode/mode_solver.py, tidy3d/web/config.py
Also:
- Made most of the helper functions and properties private to not crowd docs
- Added type annotation everywhere
=> Splitting ModeSolver.solve in some helper functions

tests/test_components.py, tidy3d/__init__.py, tidy3d/components/__init__.py, tidy3d/components/source.py
Astigmatic gaussian beam seems to work, rebased to latest develop.
Link to backend PR: https://github.com/flexcompute/tidy3d-core/pull/56
Attached is a notebook with an example.
[AstigmaticGaussianBeam.pdf](https://github.com/flexcompute/tidy3d/files/8606408/AstigmaticGaussianBeam.pdf)
=> Added simple astigmatic gaussian beam source

tidy3d/version.py, tidy3d/web/httputils.py
- max attempts for authentication
- use error message from response json if available
=> Better handling of http response errors

tests/test_config.py, tests/test_log.py, tidy3d/__init__.py, tidy3d/config.py, tidy3d/web/config.py
* freezing tidy3d components
* setting logging level
* setting web config
=> added config file

tests/test_components.py, tests/test_geo_group.py, tidy3d/__init__.py, tidy3d/components/__init__.py, tidy3d/components/base.py, tidy3d/components/geometry.py, tidy3d/components/simulation.py, tidy3d/components/structure.py
=> added GeometryGroup

tidy3d/components/simulation.py
Added extra information about symmetry plane at simulation center in the symmetry property description.
=> Symmetry documentation

tests/test_IO.py, tidy3d/components/data.py, tidy3d/components/simulation.py, tidy3d/updater.py
This is just a first stab at some updater improvements.  I figured it would be best to get this done before I lose internet in an hour.
Feel free to test, merge, or just wait.  I've tested upgrading from 1.3 -> 1.4 and also loading 1.4 -> 1.4.
=> update simulation when loading from web

tests/sims/simulation_1_4_1.json, tidy3d/updater.py, tidy3d/version.py, tidy3d/web/s3utils.py, tidy3d/web/webapi.py
Reverted #304 because the download of simulation errors.
This was perhaps not caught before because the error was caught and only logged instead of raised. I removed that try except and now if you do e.g. `pytest -ra tests/_test_webapi.py -k webapi_0` you will get an error.
Furthermore, what is the purpose of `dummy_app.py` added to the root folder?
=> Security Mitigation.

tests/_test_fit_web.py, tidy3d/plugins/dispersion/fit_web.py
Try the fitter without k_data; e.g. the first one in `tests/_test_fit_web.py`
=> Dispersive fitter for lossless media

tidy3d/components/geometry.py, tidy3d/components/grid/mesher.py
Fixing bounds computation in GeometryGroup
=> Fixing override structure when precison issue comes in

tests/test_components.py, tidy3d/components/geometry.py
@shashwat-sh could you modify this branch to try to get this test to fail? and then we can look into the issue behind it.
=> added test to check if intersections caught where two boxes touch

make_script.py, test_local.sh, tests/test_make_script.py, tox.ini
Usage:
```
$ python script.py simulation.json simulation.py
```
to turn existing `simulation.json` into a script `simulation.py`
=> added script to generate python script from json file

tests/test_sidewall.py, tidy3d/components/geometry.py
=> Support negative sidewall angle for slanted polyslab

tests/test_data_arrays.py, tidy3d/components/data/data_array.py
=> added .abs property to DataArray

tidy3d/plugins/mode/mode_solver.py
Made it hard to accidentally add a monitor with the same name
=> changed name of mode solver monitor in mode_solver.sim_data

tests/test_data_monitor.py, tidy3d/components/data/monitor_data.py
=> raise DeprecationWarning if user calls ModeSolverData.plot_field

tests/test_near2far.py, tidy3d/components/monitor.py, tidy3d/components/simulation.py
- Fixed bug in n2f exclude surfaces
- Added n2f with symmetry validator
- Added tests for both these things
=> Small n2f bug fix for excluded surfaces and added a validator

tidy3d/components/monitor.py
Also added small clarification to Cartesian monitors.
=> Fixed docstrings for n2f monitors

make_script.py, tests/sims/simulation_1_6_2.json, tidy3d/components/monitor.py, tidy3d/updater.py
https://lgtm.com/projects/g/flexcompute/tidy3d/?mode=list
=> fixes some warnings from code quality anlayzer

tidy3d/components/data/monitor_data_n2f.py, tidy3d/components/data/near2far.py, tidy3d/components/medium.py
This is #499 but with only the near2far refactoring included.
=> refactor near2far internals

tests/test_components.py, tests/test_data_arrays.py, tests/test_data_monitor.py, tests/test_data_sim.py, tests/utils.py, tidy3d/__init__.py, tidy3d/components/boundary.py, tidy3d/components/data/data_array.py, tidy3d/components/data/monitor_data.py, tidy3d/components/data/monitor_data_n2f.py, tidy3d/components/data/near2far.py, tidy3d/components/geometry.py, tidy3d/components/monitor.py, tidy3d/components/simulation.py, tidy3d/components/validators.py
Added a monitor and data structures for computing diffraction efficiency via a 2D FFT of fields. The actual computation happens in backend Python.
Backend PR: https://github.com/flexcompute/tidy3d-core/pull/153
=> Diffraction efficiency monitor

tests/test_data/test_data_arrays.py, tests/test_data/test_monitor_data.py, tidy3d/components/data/monitor_data.py
There's also a backend test that `FluxMonitor` and `FluxTimeMonitor`-s produce the same result as the same-sized field monitors when calling the `flux` method.
=> Adding flux property and dot method to field data types

tidy3d/components/data/monitor_data.py
Background: see the discussion [here](https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/72).
=> Renormalized projected fields now returned as a copy of the data

tests/test_data/test_data_arrays.py, tests/test_data/test_monitor_data.py, tidy3d/components/data/monitor_data.py
gauge selection based on overlap amplitude phase
=> new gauge selection in mode tracking + a better testing

tidy3d/components/source.py, tidy3d/plugins/mode/mode_solver.py
Changed the logger in mode_solver.py and source.py and deleted the logging module import.
=> Change from using logging module to tidy3d logger

tidy3d/components/simulation.py
Also, using `abs` instead of `real` in the comparison, and added some comments.
=> Keep the warning but make tol default

tidy3d/components/data/monitor_data.py
Also added a backend test for this.
=> Fix to symmetry_expanded_copy for colocating monitors

tidy3d/components/medium.py, tidy3d/web/webapi.py
Also, for some reason there was a pylint error that I fixed in this PR.
=> fixed typo in Lorentz.coeffs

tidy3d/plugins/mode/mode_solver.py
=> Fix field_decay_warning in mode solver with symmetry

.github/workflows/release-pre.yml
=> trigger run

README.md, setup.py, tidy3d/__init__.py, tidy3d/version.py
this way, it's conditional so we can use the same code to warn or not warn depending on the PyPI repository name.
=> log warning if tidy3d-beta is the pyPI repository name

README.md, requirements/basic.txt, requirements/dev.txt, requirements/web.txt, setup.py, tests/test_web/test_cli.py, tests/test_web/test_webapi.py, tidy3d/web/__init__.py, tidy3d/web/cli/__init__.py, tidy3d/web/cli/app.py, tidy3d/web/cli/readme.md, tidy3d/web/httputils.py, tidy3d/web/webapi.py, tox.ini
=> Add apikey auth

.github/workflows/run_tests.yml
I think this should work, and we can put into develop right away.
=> Run tests on PR into pre/ branches

tests/test_components/test_simulation.py
Added test to check that an error is raised if there is an inhomogeneous substrate
=> added test for inhomogeneous substrate

CHANGELOG.md, tests/_test_local/_test_web.py, tests/sims/simulation_1_9_0rc2.json, tidy3d/web/__init__.py, tidy3d/web/queue.py
instead of 
```py
batch = web.Batch(simulations=sims)
batch_results = batch.run(path_dir="data")
```
you can use `asyncio` [package](https://realpython.com/async-io-python/) to do
```py
batch_results = await web.async_run(sims)
```
and the simulations will run asynchronously 
uses an `asyncio.Queue` under the hood.
@joamatab
=> `web.run_async` as alternative to `web.Batch`

tests/sims/simulation_1_9_0rc2.json, tests/test_components/test_geometry.py, tidy3d/components/geometry.py, tidy3d/components/simulation.py
=> suggested changes to momchil/intersects

CHANGELOG.md, tidy3d/web/container.py, tidy3d/web/s3utils.py, tidy3d/web/webapi.py
Tested on WebApi.ipynb notebook and works as expected.
=> force progress bars to 100% when task completed

tests/test_web/test_webapi.py, tidy3d/web/container.py, tidy3d/web/s3utils.py, tidy3d/web/webapi.py
`web.run(..., verbose=False)`
`web.upload(..., verbose=False)` (etc)
`job = Job(..., verbose=False)`
`batch = Batch(..., verbose=False)`
leads to no output unless warning or error.
=> verbose option in webapi

tidy3d/web/__init__.py, tidy3d/web/webapi.py
=> Removing billed cost display; adding real_cost function for user

CHANGELOG.md, tests/test_components/test_source.py, tidy3d/components/data/sim_data.py, tidy3d/components/source.py, tidy3d/components/types.py
=> adds "val" option in `SourceTime` plotting

CHANGELOG.md, tidy3d/web/asynchronous.py
=> add simpler progressbars for `run_async` when verbose

tidy3d/components/grid/mesher.py
@tomflexcompute could you play around with some simulations with PEC and see if the auto grid generates meaningful results?
@caseyflex I think this is how this should be handled for `Medium2D` too - we can just add that to the `if isinstance(...` line. This would still try to add a mesh boundary based on the 2D medium geometry but will not refine the mesh based on the medium permittivity. Then we need to decide if we want to refine separately or not, as per our on-going discussion.
=> Ignore some mediums in mesher

CHANGELOG.md, tests/test_components/test_custom.py, tests/test_components/test_medium.py, tests/test_components/test_simulation.py, tidy3d/components/medium.py, tidy3d/components/simulation.py
=> Adjust time step size with medium property for stability

tests/test_web/test_tidy3d_task.py, tests/test_web/test_webapi.py, tidy3d/web/simulation_task.py
Works in tests and on example notebook
=> use webapi for get_run_info

CHANGELOG.md, tests/test_plugins/test_component_modeler.py, tidy3d/plugins/smatrix/__init__.py, tidy3d/plugins/smatrix/smatrix.py
Two major changes:
1. Smatrix tool returns a DataArray with dims `("port_in", "port_out", "mode_index_in", "mode_index_out", "f")`
2. Smatrix tool accepts `freqs` instead of single `freq`
=> Smatrix tool returns multi-frequency DataArray

tidy3d/web/simulation_task.py, tidy3d/web/webapi.py
Note, does not change webapi just changes docstrings and log statements
=> FlexUnit -> FlexCredit

CHANGELOG.md, tests/sims/simulation_2_0_0.json, tidy3d/plugins/adjoint/web.py, tidy3d/web/asynchronous.py, tidy3d/web/container.py, tidy3d/web/s3utils.py, tidy3d/web/simulation_task.py, tidy3d/web/webapi.py
Note: only merge if we decide to go with `verbose=True` in webapi defaults.
Ran the webapi notebook on this branch and it worked fine.
=> set verbose=True by default in webapi

CHANGELOG.md, tests/test_plugins/test_adjoint.py, tidy3d/plugins/adjoint/components/data/data_array.py
=> filter adjoint source based on amplitude relative to max

CHANGELOG.md, tidy3d/components/boundary.py, tidy3d/components/data/sim_data.py
Fixes a few warnings from docstrings that remained after 2.0
=> fix docstring tests

CHANGELOG.md, tests/test_plugins/test_mode_solver.py, tidy3d/components/mode.py, tidy3d/plugins/mode/mode_solver.py
Makes more sense to keep the setting together with the other fields against which it must be validated.
=> Move group index calculation setting to ModeSpec

tidy3d/components/source.py
Added a description of how the source is normalized.
=> Update the TFSF docstring

CHANGELOG.md, tests/test_web/test_tidy3d_task.py, tests/test_web/test_webapi.py, tidy3d/web/simulation_task.py
It seemed it was being passed with an extra `_` in the response key. This should fix #854 but needs testing.
=> fix callback_url

CHANGELOG.md, tidy3d/web/__init__.py, tidy3d/web/webapi.py
=> added web.test() to check if API key configured correctly.

tidy3d/plugins/mode/solver.py
- Using a high conductivity model for PEC regions in the mode solver, rather than a large negative permittivity
- Added internal functionality to apply incidence matrices or preconditioning in the mode solver for future testing (inactive by default, not accessible via the API)
=> Improvements to the mode solver for PEC regions

CHANGELOG.md, tidy3d/plugins/mode/mode_solver.py
Copied from #872 to rebase against pre/2.2 without confilcts.
=> Add scale option fo ModeSolver.plot_field

tests/test_components/test_custom.py, tidy3d/components/medium.py, tidy3d/plugins/adjoint/components/data/data_array.py
So I just made a few changes to generalize the custom medium properties and internals so that they work with adjoint plugin as well. Let me know if anything I did potentially messes with the workings of the regular CustomMedium (for example, I wasn't sure if each of the xx, yy, zz components could be safely assumed to have the same frequency?)
=> made custom medium adjoint work

tidy3d/components/data/monitor_data.py
To fix https://github.com/flexcompute/tidy3d/issues/860
=> Missing descriptions in monitor data classes

tests/test_plugins/test_adjoint.py, tidy3d/plugins/adjoint/components/medium.py
* Added additional pipeline tests with explicit 2D simulation size.
* Medium's inside mask is XR.DataArray for more robust broadcasting.
* Fixed a few special cases in JaxCustomMedium that broke after these changes. (essentially, before we were squeezing out size=0 dims in various places, but to be consistent, now we are just treating them as size=1 dims and not summing them out until the volume integration with the rest of the coords).
All tests passing (including new ones) and the notebook 3 is working with run_local
=> fix bugs / robust handling of 2D in adjoint plugin

CHANGELOG.md, tests/test_components/test_custom.py, tidy3d/__init__.py, tidy3d/components/base.py, tidy3d/components/data/data_array.py, tidy3d/components/medium.py, tidy3d/components/simulation.py, tidy3d/components/structure.py, tidy3d/plugins/adjoint/components/data/data_array.py, tidy3d/plugins/adjoint/components/medium.py
=> Custom dispersive medium

tests/sims/simulation_2_3_0rc1.json, tests/test_components/test_simulation.py, tidy3d/components/medium.py, tidy3d/components/simulation.py
Anything else that needs to be modified?
=> Simulation.allow_gain and a small update to the allow_gain docstring

tests/test_components/test_IO.py, tests/utils.py, tidy3d/components/medium.py
Add custom medium and STL to SIM_FULL in tests
=> Load custom medium as vacuum from json

CHANGELOG.md, tests/test_plugins/test_adjoint.py, tidy3d/plugins/adjoint/components/medium.py
Figured we might want to relax this for a potential user @xin-flex. Not sure what your thoughts are @momchil-flex or if you want to also be more strict on the total number of pixels etc. but figured I'd open the PR just to get this started.
=> remove restriction on 3D pixelated grids in JaxCustomMedium

tests/test_components/test_source.py, tidy3d/components/source.py, tidy3d/plugins/adjoint/components/data/monitor_data.py
Associated backend PR: https://github.com/flexcompute/tidy3d-core/pull/326
=> Generalized reverse interpolation for current sources

tidy3d/plugins/adjoint/README.md
=> fix some typos in adjoint developer docs

CHANGELOG.md, tests/test_components/test_viz.py, tidy3d/components/geometry.py
=> properly render point-like objects in viz

CHANGELOG.md, tests/test_components/test_simulation.py, tidy3d/components/simulation.py, tidy3d/components/validators.py
=> warn instead of error for structures out of sim bounds

CHANGELOG.md, tests/test_components/test_types.py, tidy3d/components/types.py
=> cleaner display of ArrayLike types in docs

CHANGELOG.md, tests/test_plugins/test_component_modeler.py, tidy3d/plugins/smatrix/smatrix.py
fixes #717 
Note: untested in the wild, will test on notebook tomorrow.
The details are probably not important, basically I changed from using a batch that was hacked together using pydantic validators to using a more direct run_async. This let me make more sensible method signatures in the main component modeler rather than having to abuse class methods everywhere.
=> internal refactor of smatrix tool

CHANGELOG.md, tests/test_components/test_monitor.py, tidy3d/components/types.py
should fix issue where `freqs : [null]`  passed validation in UI
=> validate ArrayLike doesnt have None or nan values

CHANGELOG.md, tidy3d/components/data/monitor_data.py, tidy3d/components/data/sim_data.py
PR https://github.com/flexcompute/tidy3d/pull/983 seem to have been dropped from develop, so I'm re-merging here.
=> Grid correction to Poynting  in 2D monitor (#839)

CHANGELOG.md, tests/test_package/test_log.py, tidy3d/config.py, tidy3d/log.py
=> Add option to control log suppression

CHANGELOG.md, tidy3d/plugins/adjoint/components/data/monitor_data.py
6 hours of work for 2 line fix...
Where do we think this should go? develop -> patch or pre/2.4?
=> fix sign flip in adjoint mode source with backwards direction

tests/test_plugins/test_mode_solver.py
Was not able to reproduce error
=> add test for mode solver to and from hdf5 with custom medium

tidy3d/components/medium.py
=> Fully anisotropic docstring fixes

CHANGELOG.md, tidy3d/plugins/adjoint/components/data/data_array.py
Note: Re-ran notebooks with this PR and they ran as expected.
=> cast `abs(JaxDataArray)` to `jnp.ndarray`

tidy3d/components/source.py
This should eliminate out of memory errors associated with computing the source spectrum when the number of time steps is very large. In my testing, it also sped up the calculation by a factor of 3 or so. The speed up increases as the number of time steps increases.
The current approach is just replacing the matrix operations with a loop over time, and reducing the number of np.exp calls as much as possible.
I also tried an FFT based approach. The frequency monitors implicitly assume the signal is zero outside of the simulation run time. In order to agree with this behavior, it was necessary to zero-pad the FFT to an extent determined by the mismatch between the frequencies at which we evaluate the spectrum and the FFT frequency grid. This was messier and may reduce precision (although …
=> Changed source spectrum calculation to work for large number of time steps

CHANGELOG.md, tidy3d/plugins/adjoint/components/data/sim_data.py
Let's try to get this into the 2.4.2 patch if that's still happening soon.
=> ensure same grid in fwd and adj sims

CHANGELOG.md, tidy3d/plugins/adjoint/components/geometry.py
just making this PR proactively in case we go this route.
=> adjoint: grab inside pixel at index=3 or 1 depending on cells

CHANGELOG.md, tests/data/example.lsf, tidy3d/web/cli/app.py, tidy3d/web/cli/converter.py
Added parser, example lsf file for testing/testing capability, and command line capability. Let me know if you want this implemented differently.
As for the converter.py file itself, let me know if you want any more comments. Most of the functions are pretty much the same, so I wasn't sure what comments/other style stuff is necessary here.
=> added lsf converter

CHANGELOG.md, tests/test_plugins/test_mode_solver.py, tidy3d/plugins/mode/mode_solver.py
=> use mode solver fields in conversion methods

CHANGELOG.md, tests/test_components/test_medium.py, tidy3d/components/medium.py
Simple functions to generate PoleResidue model from LO-TO form.
=> Added LO-TO form of PoleResidue model

CHANGELOG.md, requirements/basic.txt
Fixes #1258 
FYI @daquinteroflex
=> matplotlib >= 3.5

CHANGELOG.md, tests/test_plugins/test_component_modeler.py, tidy3d/plugins/smatrix/smatrix.py
=> add `ComponentModeler.plot_sim_eps()`

CHANGELOG.md, tests/test_plugins/test_adjoint.py, tidy3d/plugins/adjoint/components/simulation.py
warn if nonlinear spec encountered in
* `JaxSimulation.medium`
* `JaxSimulation.structures`
* `JaxSimulation.input_structures`
Also some fixes to the changelog.
=> adjoint warn nonlinear

tidy3d/components/heat/simulation.py
to account for https://github.com/flexcompute/tidy3d-core/pull/473
=> Remove heat warning

CHANGELOG.md, tests/sims/simulation_2_5_0rc3.json, tests/test_components/test_monitor.py, tidy3d/components/field_projection.py, tidy3d/components/monitor.py
Backend PR: https://github.com/flexcompute/tidy3d-core/pull/468
Addresses this issue: https://github.com/flexcompute/tidy3d-core/issues/395
Notebook that demonstrates this: https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/329
=> Spatial filtering of far fields by windowing near fields

tidy3d/material_library/material_library.py
=> Rename Silicon in material library

tidy3d/components/mode.py
We actually allow for negative bend radius, so we need to validate the magnitude.
=> Allow bend_radius to be negative, but not close to zero

.github/workflows/run_tests.yml, .github/workflows/sync-to-readthedocs-repo.yaml, .pre-commit-config.yaml, docs/api/heat/boundary_conditions.rst, docs/api/heat/discretization.rst, docs/api/heat/index.rst, docs/api/heat/mediums.rst, docs/api/heat/monitor.rst, docs/api/heat/output_data.rst, docs/api/heat/simulation.rst, docs/api/heat/source.rst, docs/api/index.rst, docs/api/plugins/index.rst, docs/conf.py, docs/development/index.rst, docs/development/project_structure.rst, docs/development/release/flow.rst, docs/development/release/index.rst, docs/development/release/notebooks.rst, docs/development/release/requirements.rst, docs/development/usage.rst, docs/lectures/index.rst, poetry.lock, pyproject.toml, tests/full_test_notebooks.py, tidy3d/web/cli/develop.py
- Again improve the develop CLI command
- Add the codespell precommit hook.
- Try to automate the sync-action to get triggered on any pre/* deployment, and to get out the existing branch name. Need to test this
- Fix minor pre/2.5 conflicts that got badly resolved.
- Add sphinx emoji to begin sprinkling around in a reasonable fashion
- CLI commands for notebooks updates and remote builds, improved relevant docs
=> Quick pre/2.6 patches

CHANGELOG.md, docs/api/plugins/design.rst, docs/api/plugins/index.rst, tests/test_plugins/test_design.py, tidy3d/plugins/design/README.md, tidy3d/plugins/design/__init__.py, tidy3d/plugins/design/design.py, tidy3d/plugins/design/method.py, tidy3d/plugins/design/parameter.py, tidy3d/plugins/design/result.py
For a detailed description, see
https://github.com/flexcompute/tidy3d/blob/0297433e864125e0fcfa02af54b488212b032a8e/CHANGELOG.md
=> design space exploration plugin

CHANGELOG.md, tests/test_components/test_medium.py, tidy3d/__init__.py, tidy3d/components/medium.py
=> from_nk to support arbitrary nk values

tests/test_components/test_packaging.py, tests/test_data/_test_datasets_no_vtk.py, tests/test_data/test_datasets.py, tidy3d/components/data/dataset.py, tidy3d/components/geometry/base.py, tidy3d/components/geometry/mesh.py, tidy3d/components/geometry/polyslab.py, tidy3d/components/geometry/primitives.py, tidy3d/components/types.py, tidy3d/components/types_extra.py, tidy3d/packaging.py
Just focused on restructuring to on-the-fly imports in a general way. I think it'd be good to benchmark to make sure it's any better than before, but will add the a benchmarking utility as well on pre/2.6 as no develop CLI on this
=> FEAT: Generalisation of large imports version 1 

tests/test_components/test_heat.py, tidy3d/components/heat/simulation.py
Backend https://github.com/flexcompute/tidy3d-core/pull/496
=> Allow stl in heat solver

poetry.lock, pyproject.toml
Released `m2r3` to PYPI. Think it should work fine now
=> FEAT: Sorted out the packaging of m2r3 :runner: 

CHANGELOG.md, tidy3d/plugins/adjoint/components/data/monitor_data.py, tidy3d/plugins/adjoint/utils/penalty.py
also fixes the 1/um in the units
=> ignore diffraction amps of NaN in adjoint source

CHANGELOG.md, tests/test_web/test_env.py, tidy3d/web/core/environment.py, tidy3d/web/core/http_util.py
@lei-flex @tylerflex  There is a pr that users can set https ssl version, the ticket from @lei-flex  https://flow360.atlassian.net/browse/SCEM-5072
=> Update the minimum tls version for python client to avoid https shake verify issue.

.github/workflows/run_tests.yml, .github/workflows/sync-to-readthedocs-repo.yaml, .gitmodules, README.md, docs/404.rst, docs/development/documentation.rst, docs/index.rst, tidy3d/constants.py
=> FEAT: Further docs improvements :cook: 

tests/test_data/test_sim_data.py, tidy3d/components/base_sim/data/sim_data.py, tidy3d/components/data/sim_data.py
this happened again when triggered in a slightly different context.
=> fix another obscure error if val not supported in SimData.plot_field

.github/workflows/test_develop_cli.yaml
Fixes the test-develop-cli action that has been failing for most people
=> PATCH: Poetry dev github actions :pill: 

CHANGELOG.md, tests/test_plugins/test_adjoint.py, tidy3d/plugins/adjoint/utils/penalty.py
notebook PR: https://github.com/flexcompute/tidy3d-notebooks/pull/46
=> adjoint util erosion-dilation penalty

docs/api/charge/index.rst, docs/api/charge/mediums.rst, docs/api/heat/mediums.rst, docs/api/index.rst, docs/api/mediums.rst, docs/api/submit_simulations.rst, docs/conf.py, docs/install.rst, poetry.lock, pyproject.toml
@momchil-flex we might have to merge this into latest since the link fixing this morning has identified these issues. The code should be the same in PyPi but we have to update this documentation. Not sure what you think?
=> FIX: Post 2.6 release :rotating_light:

CHANGELOG.md, tidy3d/components/base_sim/data/sim_data.py, tidy3d/components/data/sim_data.py
found another bug (introduced by me when I fixed a different bug). was plotting `re` in `magma` cmap.
=> fixed plot_field cmap for re and im

CHANGELOG.md, tidy3d/web/api/tidy3d_stub.py, tidy3d/web/api/webapi.py
Fixes #1483, except the last point (add the tidy3d.log file to the divergence email).
=> Directing users towards log if warnings found or simulation diverged or errored

CHANGELOG.md, tidy3d/plugins/adjoint/components/geometry.py
=> fix adjoint "edge" case :P

poetry.lock, pyproject.toml
=> FIX: Versioning and fix numpy version :arrow_up_small:
